### ISSUE TITLE
Add donation options to barter.vg

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#10]
Barter.vg is a awesome website and it doesn't run any ads. The hard work that has been put into it shows and it seems to be entirely self-funded. Therefore, it's only fair to reward you hard work and help lighten the costs that come with it. So, I am suggesting donating options, such as patreon, paypal.me and bitcoin. <3

**Comment by bartervg** [comment]
That would become a distraction.

**Comment by Revadike** [comment]
A distraction? Could you please elaborate?

**Comment by bartervg** [comment]
I don't doubt that it's convenient to setup any of those services, but to use any of them effectively, it requires time and attention.

In addition, there are far more effective ways to support the site by volunteering time and skills. Several do that and those efforts are much more valuable. Therefore, I'd prefer to focus on that.

**Comment by Revadike** [comment]
Can I help with programming? :)

**Comment by bartervg** [comment]
You're already providing stress testing and adversarial modeling
