### ISSUE TITLE
"Add to library" button on scratchpad and bundle pages

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#101]
# Describe the problem that this feature would improve
It's annoying to open each item in let's say a Groupees bundle manually and press "Add to library" from each item's page instead of selecting all and click "Add to library".

![image](https://user-images.githubusercontent.com/956878/76706851-d4fdba80-66ea-11ea-9ecf-0a716c226915.png)

Groupees, Itch.io, GOG and other non-syncable items have to be manually added to your library. 

## Describe a solution you'd like
Add a "Add to library" button on bundle pages and from the scratchpad.

Bonus suggestion: add a "Select all" button for each tier, so that you can select individual tiers with one click.

## Examples of similar features
"Blacklist" button, "Wishlist" button

**Comment by bartervg** [comment]
Added 
![image](https://user-images.githubusercontent.com/28576132/76919915-9578cf00-68a0-11ea-8a6a-b26c6d720997.png)

but without any when-to-appear logic -- the library button will appear on every bundle. Another long-requested feature, if library is custom addition, switch to sync if it appears in sync later. This has the advantage of tracking revoked.

**Comment by Luckz** [comment]
> switch to sync if it appears in sync later. This has the advantage of tracking revoked.

OTOH if it does not appear in sync anymore, yet still appears in the latest `custom` (now: `userdata`), it should be switched back to that instead of going to revoked.
