### ISSUE TITLE
Clarify usage of "Music" item type / possible mass-edit from "Media" to "Music"

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#103]
# Describe the problem that this feature would improve
Recently Steam added their new "Music" app type. Should this item type be reserved for Steam items only?

We have a lot of old (and new) Groupees items on the site where all the music albums use the old "Media" item type instead of the new "Music" type. Should we do a mass-edit of all items that contain the text "(music album)", and change them to the "Music" tag instead of "Media"? Or is this tag, as asked, for use with Steam items only? 

## Describe a solution you'd like
Since non-Steam items use the "DLC" item tag, it seems to me that using the "Music" item type for non-Steam music items should be OK, and therefore we could do a mass-edit as described above.

## Example items
- Steam "Music" item: https://barter.vg/i/13438/
- Non-Steam "Music" item: https://barter.vg/i/113371/
- Media item: https://barter.vg/i/101205/

**Comment by bartervg** [comment]
> Should this item type be reserved for Steam items only?  

No, the types can be used for any platform. Although there are some confusing cases, for Steam, this should be automated and objective. For other platforms, there likely isn't a definitive answer for the type.

> Should we do a mass-edit of all items that contain the text "(music album)", and change them to the "Music" tag instead of "Media"?  

Yes, this is a good idea.

**Comment by bartervg** [comment]
I searched through the Media types and changed the items that appeared to be Music into the new type. There may be some mistakes or overlooked items, but there are only 206 remaining `Media` types (and they are mainly ebooks), so the edits will be one-off edits rather than mass edits.

**Comment by Revadike** [comment]
why are you manually doing this?

**Comment by bartervg** [comment]
Manually analyzing the list of titles and then using queries such as  `title LIKE '%music album%' `

**Comment by bartervg** [comment]
This was for non-Steam items. The Steam item types are automated, but as you demonstrated, the web results, including the store page, appear to be delayed or inaccurate. SteamDB seems to be more accurate than the Steam store pages.
