### ISSUE TITLE
Certain non-Steam non-game items behave differently when adding to library

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#104]
## Describe the bug
Normally when you're on an Barter item page and press the "Library" button to add the item to your library, the page reloads and the button changes to a "Remove from your library" button + an icon to show that the item is on your library.

However, on certain non-Steam, non-game item pages, this does not happen, even though the item does get added to your library.

## Steps to reproduce the bug
1. Go to https://barter.vg/i/101205/
2. Click on "Library 📚"
3. The item gets added to your library with no visual cues on the "Library 📚" button.

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/956878/76708023-16df2e80-66f4-11ea-9127-b55726956f95.png)

**Comment by Tecfan** [comment]
Confirmed item types this happens with: Media (Groupees), Music (itch.io). I haven't done more extensive testing.

**Comment by bartervg** [comment]
This is an interesting bug. There is simple logic for Steam items, strange convoluted logic for everything else. I don't remember or understand why. At the risk of https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence, I removed this convoluted logic.

![image](https://user-images.githubusercontent.com/28576132/76921146-a9720000-68a3-11ea-8821-3d5dd61f486a.png) It seems to work.

**Comment by bartervg** [comment]
Also, screenshot reminded me to change it to Music.

**Comment by Tecfan** [comment]
This issue is still persistent on this page: https://barter.vg/i/81156/

Library button stays unchanged even though the game is in your library.

**Comment by bartervg** [comment]
Humble Trove platform items are excluded from displaying all of the buttons. Unintended side effect was that it didn't check if in library or scratchpad.
