### ISSUE TITLE
Make subid tag clickable on all pages

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#105]
## Description
The subid tag is already clickable on the tradables page, but can you make it clickable (lead to steamdb) for other pages, like the item page? Shouldn't be too hard to implement.

## Example
https://barter.vg/i/72874/

**Comment by bartervg** [comment]
Good idea. Added it to the game profile pages. 
![image](https://user-images.githubusercontent.com/28576132/76981896-8e3dd980-6911-11ea-8e11-db9a9aee4e29.png)

Anywhere else missing SteamDB links?

**Comment by Revadike** [comment]
Not sure
