### ISSUE TITLE
Better™ trading notices, including expiry date awareness

### ISSUE THREAD

**Issue by Luckz** [bartervg/barter.vg#106]
# Describe the problem that this feature would improve
Warnings for past&future expiry date or revocation aren't the clearest.  
For [expiring keys](https://github.com/bartervg/barter.vg/issues/67#issuecomment-600727093) we use Activation Deadline. But once the deadline is over, and the unredeemed keys are indeed killed off by Valve, that's where we historically often used the "duplicates!!" one as we didn't have "unused keys revoked" yet. Usually we go by user reports in these cases: if some user(s) say their keys don't work anymore, we add a warning.  
Today we added an 'activation deadline' notice to an item that had to be activated in 2015, and it seems if we know that something won't redeem for sure, we should have a message that's clear at first glance.

## Describe a solution you'd like
Once we track known past & future expiry dates in the database and not in mere text fields https://github.com/bartervg/barter.vg/issues/67, we would want to use visual cues like different messages, colours, or if everything else fails tooltips, to express how critical the deadline is at the time of page rendering (proposed: `unreached, close (~7 days?), or in the past.`).  

Offer creation, offer, match, tradable screens should all be revisited for potential additional clarity about keys that are either guaranteed not to work, or unlikely to work, or won't be redeemable for long.

------
Suggested by bartervg.

**Comment by bartervg** [comment]
#108

**Comment by bartervg** [comment]
If I understand this issue accurately, it seems resolved by #142 and trading tag notes
