### ISSUE TITLE
When multiple tradables of same item, display problem in offer

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#107]
## Describe the bug
In offers, for each item, there is a list of which collection the item appears in for each user. This displays quantity, but it is inaccurate when there are multiple tradables of the same item.

## Steps to reproduce the bug
1. Add two tradables of the same item, set each to a different quantity
2. Create an offer and include one of the added tradables
3. The quantity show after `tradable` may not correspond to the quantity set to the included tradable

## Expected behavior
[img] tradable (x1, x2, 3x), library (custom)

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/28576132/77005769-bf310500-6937-11ea-9eb8-3e7ff2926b68.png)
The tradable in the offer has a quantity of two

### Additional context
Initially tested by luckz over 2 years ago

**Comment by bartervg** [comment]
If I remember this bug correctly, it was fixed.

**Comment by Revadike** [comment]
Is it related to this weirdness?

![image](https://user-images.githubusercontent.com/4411977/197556326-a4d58938-d6b8-44c2-9488-813ed28267ed.png)

**Comment by bartervg** [comment]
> Is it related to this weirdness?

Yes, that's the fix for this issue.

**Comment by Revadike** [comment]
> > Is it related to this weirdness?
> 
> Yes, that's the fix for this issue.

Well then why am I still seeing it 😅

**Comment by bartervg** [comment]
The bug was that the different quantities didn't appear. That weirdness is a feature.

![image](https://user-images.githubusercontent.com/28576132/197564928-df54eaff-4ac9-4fde-8071-6be190777c6e.png)
There are two Doctor Who Infinity tradables, but with different store tags.
