### ISSUE TITLE
Ignored users can accept multiple user offers

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#109]
## Describe the bug
An user that the sender ignored can receive and accept a multiple user offer. Ignored users should not be able to receive or accept offers from the sender.

## Steps to reproduce the bug
1. Create a multiple user offer (should work with preset offer also)
2. Craft the offer so it will appear to a specific user
3. Ignore specific user and then watch them accept offer anyway

## Expected behavior
If the sender ignores a user, that user should not receive any offers from the sender, should not accept offers, and should not comment in offers.

### Additional context
Reported several times, most recently by Nick_kharkov

**Comment by bartervg** [comment]
In addition, this applies to receiving offers from ignored users.

**Comment by Tecfan** [comment]
Bug still alive and well and annoying people.

**Comment by bartervg** [comment]
I think I see the problem, but it will take some time to fix it properly. The original fix seems to be cosmetic only.

I set the offer https://barter.vg/u/4cdb/o/3968905/ to cancelled to reduce nonstop's number of failed offers. @Tecfan thank you for reporting this. I know that nonstop reported it on Discord, but centralizing the bugs on Github does make things easier. Given the annoyance of this issue and the poorly designed fix, I'm sending bug bounties to ~~Tefan~~ Tecfan and nonstop.

**Comment by bartervg** [comment]
There are many ways to accept a multiple user offer, previous fixes dealt with the multiple-user offers appearing on the offers pages. However, they appear on game profile pages as well. When viewing the offer, nothing checks to see if the users are ignoring each other, no form manipulation required.

First step, on the server-side, block accepting of multiple user offers if either side ignores.
Second step, hide offers on the game profiles to avoid seeing an offer that cannot be accepted. In addition, hide the accept button if someone views the offer.

**Comment by bartervg** [comment]
This looks like a duplicate of #76 

> There are many ways to accept a multiple user offer

More accurately, `There are many places to see a multiple user offer`. There is one function to join offers and rather than focusing on hiding UI, the fix should have been to that function. 

> First step, on the server-side, block accepting of multiple user offers if either side ignores.

Done. Closing this issue because `First step` was taken and because it is a duplicate of #76
