### ISSUE TITLE
option to turn off multi-user offers

### ISSUE THREAD

**Issue by Luckz** [bartervg/barter.vg#118]
# What's the problem that this feature alleviates?
Paraphrased from a user request:
> I've received a four digit amount in 5 years and every single one of them was resellers trying to dump their unpopular goods for my valuables.

## Describe a solution
Profile option to disable receiving or seeing multi-user offers. Default: multi-user offers enabled.

## Examples of similar features
Restricting tradables by type/attribute, restricting items per offer, turning off offer comments, etc.

**Comment by bartervg** [comment]
#109 #96 #76 I think fixing existing bugs could alleviate some of the problem, but a complete solution would be preference settings.

**Comment by Luckz** [comment]
Also requested by https://steamcommunity.com/groups/bartervg/discussions/2/3159763879055611255/

**Comment by bartervg** [comment]
I was going to defer this until better preference system and improved multiple user offers, but given the popular demand, rushed out (+17 days) the preference with minimal testing. 
![image](https://user-images.githubusercontent.com/28576132/79385194-2db4b300-7f36-11ea-9120-489e862cae69.png)
