### ISSUE TITLE
Steam app-title autosyncing erases work done: Ideas how to do better

### ISSUE THREAD

**Issue by username0123456789** [bartervg/barter.vg#122]
### Problem description

Fixing incorrect/misleading Steam app titles by editing the automaticly synced Steam app titles on item profile pages is currently not ideally implemented because the syncing erases the changes made in many cases.

### Idea how to do better

**- Autosynced title values (app_title and Store_title) on Steam App item-profile pages should not be editable**

**- Add "enabled/disabled" boolean for app_title (aka title) and Store_title (aka title_alt).** (default being enabled of course.)

Applying disabled-states for the synced titles would have following effects:

**- if Store_title is disabled, app_title is used exclusively and store title is no longer shown.** 
_This would take care of lots items where Steam Store redirect causes wrong or misleading store title, for example: https://barter.vg/i/4554/ https://barter.vg/i/67390/_ 

**- if app_title is disabled, but store_tile is not, then store_title is used exclusively and app_title is no longer shown.** 
_This would take care of some rare cases where the title from http://api.steampowered.com/ISteamApps/GetAppList/v2/ is problematic but synced store title would be better. I don't recall an explicit example at this time, but there are such cases._

**-  if both app_title and store_title are disabled, then there must be manually entered title. The already existing title_distinguisher (aka title_extra) field could be used as the override title in this case, or alternatively create new database entry field where manually entered titles get stored, so then title_distinguish would be continued to be used as it is used currently.**
_This would take care of apps that don't exist in http://api.steampowered.com/ISteamApps/GetAppList/v2/ and often these same apps don't have Steam Store page (and some not even Steamcommunity page) and/or there is redirect to another misleading item. This concerns mostly uncommon items like retail only DLCs, advertising apps and decommissioned games, but there are also common items included in bundles in particularly! All of this kind of items that could be titled properly with this workaround, without having the frustration that syncing erases all the work done later.
Examples where manually entered title override needed: https://barter.vg/i/14410/ https://barter.vg/i/39558/ https://barter.vg/i/112975/ https://barter.vg/i/112998/ https://barter.vg/i/108887/_

**Comment by bartervg** [comment]
This is partially addressed with `Sync with store and API` and setting it to `Do Not Sync`. 

I set https://barter.vg/i/14410/ https://barter.vg/i/39558/ https://barter.vg/i/112975/ https://barter.vg/i/112998/ https://barter.vg/i/108887/ to Do Not Sync.

**Comment by bartervg** [comment]
I added locks to both app and store title, similar to https://github.com/bartervg/barter.vg/issues/123 that should prevent overwriting of titles unless unlocked.

**Comment by username0123456789** [comment]
Thanks! Seems to be working as intended, so far I haven't noticed titles getting replaced anymore after setting them locked. 

Now that the store title can be blanked and locked, there is much less need for "Do Not Sync" I think. Is there actually any need for "Do Not Sync" anymore, now that titles can be locked regardless?  (I know the tag section is a mess for some items but thanks to the apptype value (as long as it's correct) most of the problematic items like trailers can be easily excluded.)

Regardless, I will now start keeping better log of title, apptype and other changes I make to item pages, so in case anything gets lost again, at least the fixes I have done will be stored separately.

Btw. The "🔍 Title Matches" section towards the bottom of the item pages is very useful sometimes, not usually but sometimes forget its existence. Most of the previously fixed, previous titles, common typos etc aka titles seem to be preserved there for the most part.

**Comment by bartervg** [comment]
I have been occasionally uploading types and titles in https://github.com/bartervg/barter.vg/tree/master/data
