### ISSUE TITLE
Display quantity of items on offers section

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#13]
Current layout: 
![image](https://user-images.githubusercontent.com/28576132/60367460-45797580-99bc-11e9-9e97-5329b416c6cb.png)

Proposed:
![image](https://user-images.githubusercontent.com/28576132/60367508-5a560900-99bc-11e9-9662-33dffbc85cbf.png)

Suggestion from Doge

**Comment by Revadike** [comment]
Will this also work for multiple game copies?

**Comment by bartervg** [comment]
Sorry to Doge that this took so long to implement despite being rather simple. 

Previously:
![image](https://user-images.githubusercontent.com/28576132/71838270-6c5ce680-3086-11ea-9076-3262fa210a2e.png)
![image](https://user-images.githubusercontent.com/28576132/71838288-77b01200-3086-11ea-8d24-2e428a543e34.png)

Now:
![image](https://user-images.githubusercontent.com/28576132/71838307-826aa700-3086-11ea-98d2-350ef07b64a1.png)
![image](https://user-images.githubusercontent.com/28576132/71838317-8991b500-3086-11ea-8352-cf89d407ce04.png)

> Will this also work for multiple game copies?

Yes.
