### ISSUE TITLE
"Beta key revoked" giveaways needs $0:β⌫ symbol in trade offers

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#135]
# What problem does this feature address?
"Free beta key that deactivates" giveaways have the following symbol in trade offers:
![image](https://user-images.githubusercontent.com/956878/82143136-d6aa4280-9841-11ea-8c20-e2cb01b039fb.png)

However, "beta key revoked" giveaways only has the normal $0 symbol:
![image](https://user-images.githubusercontent.com/956878/82143145-e45fc800-9841-11ea-9faa-ae812a1fc52f.png)

Now it looks like Trident's Wake has been given away, when it reality, it is even "less given away" than the former game. 

## Describe a solution
"Beta key revoked" giveaways should have a $0:β(⌫?) symbol.

**Comment by bartervg** [comment]
This was my mistake for not configuring the new `Beta key revoked` giveaway type. I updated the symbol to your suggestion, but that led to two lines. Therefore, I shortened it to `⌫:β` 
![image](https://user-images.githubusercontent.com/28576132/82395979-c3060400-9a1a-11ea-9542-7525689f7eae.png)
