### ISSUE TITLE
Send multiple offers to the same user

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#136]
## What problem does this feature address?
I want to offer a user different items for different items, which is not possible in a single offer.
For example, I want to send multiple "multiple users"-offers for each of my tradables.

## Describe a solution
Allow multiple offers to the same user.

## Examples of similar features
Lestrades allows this.

**Comment by Tecfan** [comment]
Yes, 100% please. I very often want to split up my $0 for $0, DLC for DLC, bundle game for bundle game and higher tier game for higher tier game trades. Now I have to wait for one to complete before I can send offers for other types of games.

**Comment by bartervg** [comment]
I rarely see complaints about receiving too few offers, the complaints seem to be about too many offers, therefore I'm skeptical of eliminating the one pending offer per user principle.

More than one multiple-user or no-specific-user offer could be useful. However, it would be a lot of offers to manage if it's one per tradable.

> I very often want to split up my $0 for $0, DLC for DLC, bundle game for bundle game and higher tier game for higher tier game trades. 

I'd rather attempt to do this with more offer options than to allow multiple offers to the same user. Although more difficult to structure, more offer options seem preferable to receiving more offers.

**Comment by Revadike** [comment]
I can never have enough received offers. Please let them come.

Anyway, a solution is a setting for each user to restrict only 1 offer per individual or not.

**Comment by Tecfan** [comment]
I support an option to allow multiple offers, that way it will only be a thing for power users.

**Comment by bartervg** [comment]
Despite `wontfix`, several changes. 

You can now send up to 2 offers to multiple users and 2 to no specific user. I had hoped to improve offers before increasing the limit, but might as well test that which can be done now. Limit could increase as offers improve and outstanding bugs fixed.

I'm surprised that paused offers didn't accidentally break the 1 pending offer per user. I hadn't tested that until reviewing this.
