### ISSUE TITLE
Delete individual trading tags on item pages

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#137]
# What problem does this feature address?
Due to my growing tradable list, I have started to edit my trading tags on item pages instead, as reloading the tradable page takes a lot of time and is therefore inefficient. However, the very useful red X on individual trading tags are not present on the item page. 

## Describe a solution
I would like the red X to delete individual trading tags on item pages (/i/) as well.

## Examples of similar features
Removal of individual tags in your tradables list.

**Comment by bartervg** [comment]
`X` remove button added to the profile page

![image](https://user-images.githubusercontent.com/28576132/82403500-fce00600-9a2c-11ea-8ef5-eb5228c631ab.png)
...
![image](https://user-images.githubusercontent.com/28576132/82403510-04071400-9a2d-11ea-9b3d-5349f94e847f.png)
....
![image](https://user-images.githubusercontent.com/28576132/82403522-0a958b80-9a2d-11ea-84da-261268d5932c.png)
...
![image](https://user-images.githubusercontent.com/28576132/82403535-11bc9980-9a2d-11ea-92be-a7c4f8796423.png)
...
![image](https://user-images.githubusercontent.com/28576132/82403543-17b27a80-9a2d-11ea-9b42-2fd82033655b.png)
