### ISSUE TITLE
https://barter.vg/giveaway should redirect to https://barter.vg/giveaways

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#138]
# What problem does this feature address?
It would just be convenient for those times you try to get to the overview of giveaways by guessing the URL. Now it just gives you a white error page if you get it wrong. It's not that easy to remember that individual giveaways have /giveaway/xxxx url while the overview page is /giveaways.

## Describe a solution
https://barter.vg/giveaway/ should redirect to https://barter.vg/giveaways/

**Comment by bartervg** [comment]
https://barter.vg/giveaway/ `200`
