### ISSUE TITLE
Giveaway pages gives HTTP Error 500 or does not fully load

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#141]
## Describe the bug
Sometimes when accessing pages under the /giveaway folder, you get HTTP Error 500. For me it's about 50% of the time. Loading the inactive giveaways overview is almost impossible to do without getting this error. 

Sometimes the individual giveaway pages are only loaded about 50%, but you don't get errors.

This happens when trying to access individual giveaways, like https://barter.vg/giveaway/6374/, and when trying to add new giveaways or items as a user with access to those functions. I would say that a successful viewing of an individual giveaway page will happen about once per 10 refreshes.

These errors have started occurring quite recently.

**I do not have this issue on my alt.**

## Steps to reproduce the bug
1. Try to load https://barter.vg/giveaway/6374/
2. Sometimes it loads, sometimes it gives HTTP ERROR 500 and sometimes it just doesn't load fully.

## Expected behavior
Giveaway information is showed.

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/956878/82372092-a28a7980-9a1b-11ea-8840-b1da1b23d498.png)
![image](https://user-images.githubusercontent.com/956878/82372307-0dd44b80-9a1c-11ea-99ec-bcff854ba8f2.png)
(nothing below this part of the page loads)

### Device (if applicable)
Happens both with or without Enhanced Barter activated. I use Chrome.

### Additional context
I have the "giveaway" flag.

**Comment by bartervg** [comment]
I can't reproduce this, so I assume the problem is a large wishlist / library side effect. I believe this was a problem with the bundle page also. Therefore, applied the same fix: if Tecfan, don't load wishlist. 

However, this isn't a sustainable fix as active other users will grow to Tecfan-size given enough time.

**Comment by Tecfan** [comment]
Working 100% of the time now.
