### ISSUE TITLE
Activation deadline date and automatic removal

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#142]
# What problem does this feature address?
Tradables may have activation deadlines. Although there is a tag for this, there is no indication of the date or automatic removal after the deadline.

## Describe a solution
> Allowing users to set when particular tradeables get removed from barter
As recommended by Blur, this could be done using the Unix time as the integer for the activation deadline.

## Examples of similar features
The subID tag converts the integer into a SteamDB link.

**Comment by bartervg** [comment]
expanded to show full values
![image](https://user-images.githubusercontent.com/28576132/82409360-8bf41a80-9a3b-11ea-8637-2709ad8700dc.png)
then displays YYYY-MM-DD on the collection page
![image](https://user-images.githubusercontent.com/28576132/82409237-4df6f680-9a3b-11ea-9173-623560f12033.png)

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/82420505-c961a380-9a4d-11ea-9bc3-8a57a9574cc0.png)
Checks every hour for activation deadlines with a time that has past within the past hour. Then changes quantity to 0 and posts to the collection feed.

**Comment by Revadike** [comment]
I already did this for my curator items, but it still doesn't show for me. Am I setting the input json correctly?
```js


    offers.forEach((offer) => {
        json[`app/${offer.appid}`] = {
            "item_type": `curator`,
            "retail_id": 1,
            "quantity": offer.quantity,
            "tags": {
                "402": offer.expire
                // "369": `prefer`
            }
        };
    });
```

**Comment by bartervg** [comment]
What's an example of the actual input JSON that produces?
I tested 
```javascript
{ "app/212680": {
        "item_type": "curator",
        "retail_id": 1,
        "quantity": 1,
        "tags": {
            "402": 1590004441
        }
    }
} 
```  

and that worked 
![image](https://user-images.githubusercontent.com/28576132/82491265-6ce49f80-9ab2-11ea-9a75-b263f496a21a.png)

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/82492428-2c862100-9ab4-11ea-9e14-9e0e4f7bbb58.png)
![image](https://user-images.githubusercontent.com/28576132/82492437-33149880-9ab4-11ea-8eca-e387234e687b.png)

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/82497346-6116ce80-9aee-11ea-8d99-8b02eaa3d8a7.png)

**Comment by Revadike** [comment]
Javascript uses ms instead of seconds, hence the mistake.

**Comment by Tecfan** [comment]
This is buggy:

![image](https://user-images.githubusercontent.com/956878/94559398-78ff1b80-0261-11eb-9522-a8be02509686.png)
