### ISSUE TITLE
Store thumbnails need titles with store name on item pages

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#144]
# What problem does this feature address?
![image](https://user-images.githubusercontent.com/956878/82385244-edaf8700-9a31-11ea-9af9-3971f8323df9.png)

I tried finding out which store the 4th tradable (the black thumbnail) was from, but could not find out without going into the source code or my tradable collection as when I tried to hover the image, no helper text popped up like it does on trading tags.

## Describe a solution
Add a title to the `<img>` thumbnail on i/ pages.

## Examples of similar features
Add a title to the `<img>` thumbnail.  This is done in the tradable collection on profile pages.

**Comment by bartervg** [comment]
Title added to the `img` tag
![image](https://user-images.githubusercontent.com/28576132/82386608-d4dbad00-9a02-11ea-81c8-4c669542a7d9.png)
