### ISSUE TITLE
Not possible to delete Relevant Sites entries by deleting the value from the input fields

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#145]
## Describe the bug
If you try to remove one of the values from the "Relevant Sites" inputs, they will just re-appear after you press "Update All URLs". It is thus not possible to remove relevant sites URL's. 

My Steamtrades Trade topic has been
![image](https://user-images.githubusercontent.com/956878/82436774-a6a7ad00-9a96-11ea-8917-dd0f11e760f2.png)
for a long time now because if I just empty the whole input field, it just gets reset back to what it was before.

Empty value should be stored?

## Steps to reproduce the bug
1. Go to your profile page
2. Try to remove one of your Relevant Sites
3. You can't

## Expected behavior
Your trade link value is removed and is empty

**Comment by bartervg** [comment]
Empty strings were ignored and nothing updated. Now, empty string should delete the link.

**Comment by Revadike** [comment]
Maybe having a ❌ icon next to it to make it easier for people to understand how to delete them

**Comment by Tecfan** [comment]
See also: https://steamcommunity.com/groups/bartervg/discussions/1/2943620809083519936/
