### ISSUE TITLE
Option to not go automatically unavailable for expiring offers

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#146]

**Comment by bartervg** [comment]
This is a small disincentive to allowing offers to expire. The benefit is to other side of the offer and potential traders. I don't plan to change this. 

In the example you mentioned, the fix would be to change the side to act and place the responsibility on the other party. A `I'm waiting for the other side to act` button. I do plan to add this.

**Comment by Revadike** [comment]
Isn't the increasing percentage expired statistic already a disincentive? I just find it annoying I have to find out I was unable to receive potential offers for x amount of time, just because some offer expired.

**Comment by bartervg** [comment]
This also serves to reduce expired offers if someone forget to set not available and continues to receive offers even as old ones expire. The fix for this will be the option to change the side to act and thus the responsible party for the expiration.
