### ISSUE TITLE
Some DLC's shows up as Music on Barter item pages

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#148]
## Describe the bug
As discussed on [Discord](https://discordapp.com/channels/329829406153375755/438406560222281738/713765374818254879), some barter "Music" type apps, are not actually "Music" apps, but "DLC" apps.

This is due to the API reporting them as being "Music" when they really are not. Probably publishers and developers has set their store layout to music, but not updated their app types.

I'm not sure if there is very much to do about this, but creating this issue to track it. Maybe contact Valve? Alternatively, could run a check with steamdb to double check app type for items that Steam API reports as "Music".

As a precaution, some sort of warning could be added to "Music" type items on Barter to make sure that the traders double check the real app type of their tradables.

Here are some examples (I almost sent out trade offers for these without owning the base game, so that could have been _disastrous_): 

- https://barter.vg/i/69395/
- https://barter.vg/i/69235/
- https://barter.vg/i/76804/
- https://barter.vg/i/46761/
- https://barter.vg/i/70791/

## Steps to reproduce the bug
1. Go to https://barter.vg/i/69395/
2. See that it is "Music"
3. Click the steamdb link at the bottom of the page
4. See that it is actually "DLC"

## Expected behavior
Barter correctly labels items

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/956878/82739291-c2cd7780-9d3e-11ea-9881-79bcd31f5508.png)

### Additional context
Context for those that don't know: Separating DLC and Music is quite important, as activating "Music" apps do not require the base on Steam, while activating "DLC" apps on Steam without the base game is impossible.

**Comment by bartervg** [comment]
I'm not sure how to fix this automatically. Given SteamDB's accuracy, it is possible, but not sure I could feasibly replicate that.
Instead, I've manually overridden the types using the feature described in #123 
![image](https://user-images.githubusercontent.com/28576132/82777114-2fb63f80-9e1b-11ea-8b8e-2daedb614d74.png)

**Comment by Tecfan** [comment]
https://barter.vg/i/74421/

**Comment by Tecfan** [comment]
https://barter.vg/i/18701/

**Comment by Tecfan** [comment]
https://barter.vg/i/46658/

**Comment by Luckz** [comment]
> https://barter.vg/i/18701/

This at least now is a music app.

![image](https://user-images.githubusercontent.com/224748/106522471-1607e480-64e0-11eb-8293-979e2c46fc49.png)

I have changed it (back?).

**Comment by bartervg** [comment]
Has this remained a problem?
I see that https://barter.vg/i/69235/ remains DLC despite the music icon.

**Comment by Tecfan** [comment]
Everything I checked looks correct.

Here is the opposite happening: https://barter.vg/i/15463/

But that's a Steam problem

**Comment by bartervg** [comment]
/remind me to check the music/DLC mis-characterization problem in six months

**Comment by bartervg** [comment]
/remind Tecfan to check the music/DLC mis-characterization problem in six months
