### ISSUE TITLE
Edit offer after accepted ~~or completed~~

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#162]
# What problem does this feature address?
Occasionally, offers will change due to keys not working (or key tracking systems not working) and the games exchanged are not accurately reflected in the completed offer.  

## Describe a solution
After accepting an offer, have the ability to submit corrections, but show the original offer and changes.

## Examples of similar features
Bundle chart feed

**Comment by Revadike** [comment]
Important is to have some type of grace period where this option is available. If you have the ability to edit ancient trades, it will be prone to abuse. 

Edit (2021):
Not sure what I meant here. Trades aren't support to stay open for a long time anyway.

**Comment by Luckz** [comment]
> Important is to have some type of grace period where this option is available. If you have the ability to edit ancient trades, it will be prone to abuse.

Certainly both parties would have to agree to the modification.

**Comment by bartervg** [comment]
After a long time of being grayed out on the pulldown, `agreed to modify` is selectable. 

This feature does not apply to completed offers. `agreed to modify` must happen prior to completion (hence the issue name change). It is located in the failed reason pulldown.
![image](https://user-images.githubusercontent.com/28576132/208753047-c7eee6d4-ee1d-4e97-bee7-b4169e3b44b1.png)

After both sides agree to modify, the offer resets to `Creating...`. The original sender of the offer must do the modifying. It is the same interface as a new offer except that the cancel and discard option is not available.
`To cancel now: send offer, fail, agree to cancel. You have up to 3 days to modify and send. After which the offer automatically changes to expired.`
Both sides must agree to modify, then send and accept the offer. It would be possible to then agree to modify and repeat indefinitely. If a user does not act, the offer will expire.
