### ISSUE TITLE
Custom Homepage

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#164]
# What problem does this feature address?
When I go to https://barter.vg, I'd like to reach my favorite page immediately, instead of having to navigate to it every time.

## Describe a solution
Have an option where people can set their default home page, and every time you visit `https://barter.vg` it will redirect you to your set subpage.

**Comment by bartervg** [comment]
> my favorite page

What is your favorite page?

**Comment by Revadike** [comment]
The offers page

**Comment by bartervg** [comment]
Why not go to https://barter.vg/u/48e/o/ or bookmark that instead of barter.vg?

**Comment by Revadike** [comment]
> Why not go to https://barter.vg/u/48e/o/ or bookmark that instead of barter.vg?

I am.

**Comment by Revadike** [comment]
Sad

![image](https://user-images.githubusercontent.com/4411977/197559441-b01f2b14-e53f-461f-912b-febcd87c5dc4.png)

![image](https://user-images.githubusercontent.com/4411977/197559539-a89df34a-a34a-46fa-85e6-6d28c31b054c.png)

**Comment by bartervg** [comment]
But Barter.vg isn't a program that requires a restart. What need is there to make barter.vg go to a different URL, when you can simply go to that different URL?
