### ISSUE TITLE
Bundle addition user suggestions

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#167]
# What problem does this feature address?
Many bundles and specials are hard to keep track of given the resources we have for bundle management (2 users?). This leaves many older specials outdated. 

## Describe a solution
Users can suggest item additions to bundles via the bundle page or game page in a GUI (not text input please). These can be approved or disapproved with 1 click by bundle moderators/admins. 

This should especially be useful for specials like GMG XP rewards, Lootboy items, DIG gem rewards (this special does not exist yet), etc. It would also lessen the amount of forum/discord pings and PM's.

**Comment by bartervg** [comment]
This exists, although rarely used, in non-GUI as bundle notes. I thought it had been disabled, so no surprise that it's easy to miss.
![image](https://user-images.githubusercontent.com/28576132/105913816-691efa80-5ffb-11eb-9a0c-763d0b08070e.png)
For bundle editors, listing the apps as CSV is easier than a new GUI interface.

Bundle notes are sent to #bundles_notes

**Comment by bartervg** [comment]
Bundle notes was restricted to those with at least 100 completed offers. I reduced this to 1.
