### ISSUE TITLE
Add "not revoked" trading tag

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#173]
# What problem does this feature address?
For clarity's sake, a "not revoked" trading tag should be added. When a game is revoked, there's most often a global "revoked" trading tag on the tradable, even though you have the game from a non-revoked source. In these circumstances, a "not revoked" trading tag will be of great help. 

## Examples of similar features
"not beta" trading tag

**Comment by Tecfan** [comment]
On pages like this it is obvious that we need a "not revoked" trading tag: https://barter.vg/i/29826/

**Comment by Tecfan** [comment]
With the new Overfall keys being distributed on Fanatical, this "not revoked" / "replacement key" trading tag suggestion has renewed interest from the likes of *checks notes* the original submitter.

**Comment by bartervg** [comment]
`replacement` and `not revoked` tags added
