### ISSUE TITLE
Move "Steam Item" to immediately under "Steam games" in the offer screen

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#175]
# What problem does this feature address?
Can this part (see screenshot) be moved to immediately under Steam games? I feel like it makes more sense than having origin, groupees, humble store etc between steam games and steam items in the offer screen.

![image](https://user-images.githubusercontent.com/956878/92326638-fdd88a00-f053-11ea-8c7b-0987f0a4c20a.png)

## Describe a solution
Move "Steam Item" to immediately under "Steam games" in the offer screen

**Comment by bartervg** [comment]
2+ years to slightly modify an ORDER BY clause ☹️. 

I still don't know how to do this well though. Here's what it looked like (1 = appIDs, 2 = subIDs, 19 = Steam items),
```mysql
ORDER BY IF(platform_id <= 2, 1, platform_id) ASC
```
here's what I changed it to
```mysql
ORDER BY IF(platform_id <= 2 || platform_id = 19, 1, platform_id) ASC
```
However, sometimes this leads to the Steam Item appearing before Steam.
