### ISSUE TITLE
Add a "not combined" tag?

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#177]
# What problem does this feature address?
> do we need a "not combined"-tag? we have "only base game" tag, but this does not encompass soundtracks and other DLC's that are commonly combined with a game, but where you have a standalone key.

## Describe a solution
A "not combined" tag that can be added to e.g. soundtracks and DLC's that you have a standalone copy of in situations where it is most commonly combined with the base game. "0 combined" does not work, because people assume that the "0" is an error as nobody except me uses the number

## Examples of similar features
"not beta" tag
"only base game" tag

**Comment by Revadike** [comment]
Since tags don't do much besides being a property of a tradable, why not allow custom tags the user can define theirselves.

**Comment by Luckz** [comment]
If "only base game" exists, it could simply be renamed to "only base game / not combined"? Or is there a distinction I'm missing?

**Comment by Tecfan** [comment]
Could do it like that, but a DLC is not a game

**Comment by bartervg** [comment]
`standalone / single app`

**Comment by Tecfan** [comment]
I love this new tag, using it extensively already:

![image](https://user-images.githubusercontent.com/956878/105684561-6cc85980-5ef5-11eb-95f3-b9952bc5ccff.png)

Although it would perhaps not be necessary if #25 was dealt with (I would no longer have to add the individual DLC's as tradable when I have a deluxe edition for trade if I could get matches based on package contents instead of just package item pages). Either way, it does not really matter – the standalone tag will still help clarify things for people browsing.

**Comment by Luckz** [comment]
> `standalone / single app`

To reiterate: Is there a point having 'Only base game'?
Does it do anything that this new tag does not?

**Comment by Tecfan** [comment]
Not really, just that one does not exclude DLC's or other app types. They could be merged.

**Comment by Tecfan** [comment]
> To reiterate: Is there a point having 'Only base game'? Does it do anything that this new tag does not?

Looks like this tag is gone now.
