### ISSUE TITLE
External forms stopped working, due to CSP

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#18]
`Refused to send form data to 'https://steamcommunity.com/tradeoffer/new/' because it violates the following Content Security Policy directive: "form-action 'self'".`
Is what you get when you try to send try to press the following button:
![image](https://user-images.githubusercontent.com/4411977/60844390-6bcbbc00-a1d9-11e9-9bb4-082c94e2992f.png)
Now, I don't know if there are other external domain forms used by barter.vg, but they won't work with the current Content Security Policy directive.
Solution is to either use a link instead or allow them in your CSP directive.

**Comment by bartervg** [comment]
I changed it to a link
