### ISSUE TITLE
Get a "Search matches" button on /i/ pages when an item is in your watchlist

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#186]
# What problem does this feature address?
If you have a game in your wishlist, you get this button on the game's item page:

![image](https://user-images.githubusercontent.com/956878/92329499-0b980a80-f068-11ea-8cf8-749abdfc3246.png)

However, if you only have it on your "Watchlist", you don't get this button.

## Describe a solution
Please let watchlist users have the ability to get a "Search matches" button on /i/ pages.

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/105637774-26afbf00-5e3d-11eb-9970-f6753ee99468.png)

![image](https://user-images.githubusercontent.com/28576132/105637780-2ca5a000-5e3d-11eb-8c13-5444c0d79f1d.png)
