### ISSUE TITLE
#x0 is visually the same as #1 in the Reserve collection

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#188]
## Describe the bug
If you put your quantity to "x0" on a tradable in the Reserve collection, there is absolutely no difference from a x1 reserve tradable.

For example, the DLC here is Reserve x1, while Livelock (the game) is x0, but there is no indication of this in the Reserve collection:
![image](https://user-images.githubusercontent.com/956878/92329727-b1984480-f069-11ea-9acb-d8b3b5c6dbe0.png)

Further, here, my tradable is x0, and my reserve tradable is also x0, but only one of them has a visual cue:

![image](https://user-images.githubusercontent.com/956878/92329729-c543ab00-f069-11ea-9a91-b290661e957c.png)

## Steps to reproduce the bug
1. Add a Reserve item
2. Change quantity to x0
3. Nothing changes

## Expected behavior
x0 appears, just like "x2" or "x5" appears.

**Comment by Tecfan** [comment]
Also of note is that x2 and x5 does not actually appear either. It is impossible to know how many tradables you have of each tradable in the Reserve collection.

**Comment by bartervg** [comment]
On the item profiles, <= 0 was hidden for non-tradable collections, but positive numbers should appear. 
![image](https://user-images.githubusercontent.com/28576132/105928374-d9397a80-6013-11eb-829c-45581a229d4c.png)
![image](https://user-images.githubusercontent.com/28576132/105928388-e0f91f00-6013-11eb-8ce3-a82fd0af6cf7.png)
![image](https://user-images.githubusercontent.com/28576132/105928467-e9515a00-6013-11eb-9535-569aee83c22e.png)

For collections, I attempted to make reserve to act as tradable does, which keeps the store column and quantity displayed.
