### ISSUE TITLE
Shopping cart icon is missing in certain collections

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#189]
Tradable (correct):
![image](https://user-images.githubusercontent.com/956878/92329815-62064880-f06a-11ea-9f26-394c35d923a8.png)

Wishlist (incorrect?)
![image](https://user-images.githubusercontent.com/956878/92329838-86fabb80-f06a-11ea-9648-cafb221ab96e.png)

Blacklist (incorrect)
![image](https://user-images.githubusercontent.com/956878/92329840-8d893300-f06a-11ea-8c04-0d7791b3c18d.png)

Library (incorrect)
![image](https://user-images.githubusercontent.com/956878/92329843-95e16e00-f06a-11ea-9336-ef695af6588f.png)

Reserve (incorrect)
![image](https://user-images.githubusercontent.com/956878/92329853-a560b700-f06a-11ea-963d-1e13b532ab86.png)

etc.

**Comment by bartervg** [comment]
The logic was that the shopping cart was applicable to tradables, but not to other collections. For example, library displays the sync type and (now) the minutes played. Wishlist displays the ranking. Therefore, working as intended except for the tooltip. I removed the `store` tooltip if it's not the shopping cart icon.
