### ISSUE TITLE
Sorting by "Store" does not work in Reserve collection (and possibly other collections)

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#190]
## Steps to reproduce the bug
1. Have some items in your Reserve collection with different store tags
2. Click on # to sort by Store
3. Nothing changes

## Expected behavior
List gets sorted by Store like the tradable list does

**Comment by bartervg** [comment]
I believe this was resolved with #189 

`#` is a different column from `🛒` as shown with the sort URLs `filter=0,1,1,0` vs. `filter=0,7,1,0`. Changing the filter URL won't bring back the shopping cart if it's replaced with `#`, but it does change the sorting.
