### ISSUE TITLE
"+Steam key" trading tag

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#194]
# What problem does this feature address?
I have an itch.io tradable, which comes with a Steam included (but I only have the itch.io link). 

## Describe a solution
Would want to add a "+ 1 Steam key" trading tag or something similar to it.

Either that, or make the "combined" tag linkable to other apps/i's/subs

## Examples of similar features
+1 soundtrack
+1 DLC

**Comment by bartervg** [comment]
I dislike this idea, but cannot adequately articulate why.

Added `+ Steam key` tag.
