### ISSUE TITLE
New app type needed: Beta

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#196]
# What problem does this feature address?
Steam now supports "Beta" as an app type.

See https://steamdb.info/search/?a=app&q=&type=18&category=0

## Describe a solution
Add Beta as an app type. We need a signifier on game pages, and a new type for manual addition when creating new items on Barter.

https://barter.vg/i/128959/

## Examples of similar features
Demo, DLC, Music

**Comment by bartervg** [comment]
https://store.steampowered.com/api/appdetails?appids=1405530
Until Barter.vg uses a different means of checking App Type or Steam adds `beta` to the web API, this will remain unfixed.

**Comment by arseny92** [comment]
> # What problem does this feature address?
> Steam now supports "Beta" as an app type.
> 
> See https://steamdb.info/search/?a=app&q=&type=18&category=0
> 
> ## Describe a solution
> Add Beta as an app type. We need a signifier on game pages, and a new type for manual addition when creating new items on Barter.
> 
> https://barter.vg/i/128959/
> 
> ## Examples of similar features
> Demo, DLC, Music

Also, most of these `Playtests` have item profiles on Barter, that do not have `full game` relations to the main app profiles. When possible, complete, or automate (`Store` buttons link to main app on SteamDB).
