### ISSUE TITLE
Overview message could be a bullet list

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#199]
# What problem does this feature address?
Overview messages are in my experience seldom read. It is currently quite strictly limited to a certain, low amount of characters, and it's presented in sentences. This chunk of text can be easy to skip.

## Describe a solution
Bullet lists on the other hand gives a great, quick overview. They are more spacious and allow for short and concise rulesets for trading. It might take up some more visual space, but I think it will directly affect the global offer decline ratio, as more people will set up clear rules, and more people will read them. I think that 5/6 points should be enough. Just an idea.

**Comment by bartervg** [comment]
This could be accomplished with markdown #51 but if it's simply `more spacious` then I think this can be accomplished with line breaks, and that's just nl2br https://www.php.net/manual/en/function.nl2br.php 

Which turns 
```
• point 1 • point 2 • point 3
```
into
```
• point 1
• point 2
• point 3
```
There is potential for layout breaking, but will fix that when encountered.
