### ISSUE TITLE
Hide "I requested to cancel" option, when...

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#2]
...it was already picked by the other trader party. This will help to avoid confusion when cancelling a trade.

**Comment by bartervg** [comment]
I agree that this could avoid confusion, but I'm not sure that the other side's action should eliminate options. Although this creates combinations such as Completed / Failed, those contradiction will need another method to reconcile rather than hiding options.

**Comment by Revadike** [comment]
Has there been any other solutions implemented as of now?

**Comment by bartervg** [comment]
To prevent both sides from selecting `I requested to cancel`? What is the problem when this happens?

**Comment by Revadike** [comment]
It makes no sense?

**Comment by bartervg** [comment]
Completed / Failed doesn't make sense either, but it's possible due to disagreement. With requested to cancel / requested to cancel, it is similar but like this https://www.youtube.com/watch?v=0rpdQvuAnqM
