### ISSUE TITLE
Option to match with users who don't have their region set

### ISSUE THREAD

**Issue by Luaccs** [bartervg/barter.vg#20]

**Comment by Revadike** [comment]
Do you mean the match page should leave out region locked tradables?

**Comment by Luaccs** [comment]
You can match with people from different regions: https://i.imgur.com/MyetuDh.png but there are people who don't have their region set, this is what I mean

**Comment by bartervg** [comment]
Thank you for the suggestion. I added [ unset ] as a region. 
![image](https://user-images.githubusercontent.com/28576132/60943936-752a5680-a2b5-11e9-9a06-54c6495b9c73.png)
