### ISSUE TITLE
"Add another Reserve" button on item pages

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#202]
# What problem does this feature address?
It's not possible to add two reserve collection items (say, the same game from two different sources) from the /i/ page. 

## Describe a solution
Add a "Add Another Reserve" button next to the "Add Another Tradable" button

## Examples of similar features
"Add Another Tradable" button

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/105637593-5dd1a080-5e3c-11eb-8709-f3ac0030fac6.png)
