### ISSUE TITLE
Blacklist inheritance [possible bug]

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#210]
# What problem does this feature address?
[I have a package containing two games as tradable](https://barter.vg/i/76196/). I have blacklisted the package, but I still want the individual games in my tradeable as well. Packages in general can be worth a lot more than just a singular game.

The problem is that if I go to a bundle page, and I see a game that is included in this package in the list of games in the bundle, this game gets a "blacklist" symbol, even though the game is not blacklisted, only the package including the game.

So to conclude:
Blacklist https://barter.vg/i/76196/
Go to https://barter.vg/bundle/4193/
Observe that Iron Fisticle base game has a blacklist symbol in the bundle's game list, even though it is not in your blacklist.

## Describe a solution
If this is intended behavior, I would like to opt out. I propose a profile setting.

**Comment by Luckz** [comment]
Blacklist inheritance sounds like a bug to me.

**Comment by bartervg** [comment]
I believe this is a display issue rather than blacklist inheritance. However, I was not able to send you (Tecfan) an offer because you have Iron Fisticle in your tradables. Therefore, it's effectively blacklisted, but due to a different reason.

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/105607995-4b3d6580-5d6f-11eb-9a03-014b635fbf0d.png)
different bug

**Comment by bartervg** [comment]
Bundle icon display bug of blacklist inheritance: fixed
![image](https://user-images.githubusercontent.com/28576132/105611850-df1a2c00-5d85-11eb-8fec-4d8da99a8707.png)
The method gets all of the items from the specified collection and if Steam package, all of the included items. For backward compatibility reasons, included items have negative quantities. Therefore, to avoid displaying the blacklist icon, check that the blacklist item has a quantity > 0.

**Comment by bartervg** [comment]
Tradable x0 no longer blocks offers for that item. It is as if the item wasn't in tradable.
![image](https://user-images.githubusercontent.com/28576132/105612841-931eb580-5d8c-11eb-9c69-89fc244133d3.png)
This wasn't part of your issue, comment or create a new issue if this is unresolved or creates new issues, but I believe the original issue is solved.

**Comment by Tecfan** [comment]
Not sure if this is a side effect of the changes. I have all these games in my blacklist, but they do not have a blacklist symbol next to them:

![image](https://user-images.githubusercontent.com/956878/106272942-24c96f80-6232-11eb-9e48-7a3379c7e058.png)

I assume this is because I ALSO have blacklisted the package _i/129222_ which includes all of these apps. 

I have both _combined_ and _standalone_ tradables.

**Comment by bartervg** [comment]
Having both the package and the included games created the bug. Originally, the icon appeared if the app was blacklisted or if it was included in a blacklisted package. With the change to not show included games as blacklisted on the bundle page, the problem arose. The item IDs are saved in an array with the item ID as the index. The included games are added after the standalone items, and therefore the included games overwrite them. There's no trace of Leisure Suite Larry items being blacklisted, only the included items from the package.

The avoid this problem, there's a !isset() check before adding any included items to the array. I checked this bundle https://barter.vg/bundle/4425/ as `49c` and there are plenty of 🚫︎ icons now. I'll leave this open to confirm it's fixed.

Feel free to re-open issues when you encounter a fix that isn't fixed or breaks other things.

**Comment by Tecfan** [comment]
Seems to be working now:
![image](https://user-images.githubusercontent.com/956878/108586374-43f97f80-734e-11eb-845a-f37ff0719425.png)

Here's from a bundle where I have package blacklisted and episode one blacklisted, but not episode two, and everything is working as intended.
