### ISSUE TITLE
Include tradables when filtering

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#212]
# What problem does this feature address?
When filtering other users' collections, tradables are often not shown. Instead, every OTHER collection is included, but not tradables. Here's an example from me filtering another users' wishlist, to find out what they want from my wishlist (they were unavailable, so could not open an offer):

![image](https://user-images.githubusercontent.com/956878/104822750-362f7680-5845-11eb-9418-92a3ee1a5f81.png)

## Describe a solution
Please include tradables when filtering.

**Comment by Luckz** [comment]
You didn't really mention any problem, improvement or benefit.
If I understand the intention of the example, it looks like you want to filter your own tradables for another user. That happens on your tradable page, not their wishlist page.

**Comment by Tecfan** [comment]
As I had all my tradables in my reserve collection, I grew accustomed using other users' wishlist pages to filter things I had, that they wanted. This worked just fine, until I moved everything back to my tradables. I did not realize you could filter inactive users [that they showed up in the dropdown list] from your own tradable page, that kind of solves the problem.

I now also see that tradables DO show up in filters, it's just that my blacklist and library usually "trumps" them. When I had 10k items in reserve, they all showed up in one big list, just like filtering from my own tradable list would have done. it was very quick, easy and would not require me to almost crash Chrome by opening my tradable page lol. 

For example, these 4 items that I added to my reserve collection as a test, shows up only in reserve, but not in tradable:
![image](https://user-images.githubusercontent.com/956878/104835359-59d6d900-58a6-11eb-97ad-01b29232fe0f.png)

Also, there's some weirdness with "combined" items from my tradable list leaking into my reserve "combined" list.

Conclusion: I grew accustomed to using other users' wishlist page to filter tradables/reserve, because reserve collection is not excluding library and blacklist when filtering on wishlist pages. Now that I know about filtering my tradables for inactive users is possible from my own tradable page, this github issue is no longer of any use, unless I can re-use the post to propose that a "quick link" for filtering my tradables for another users' wishlist would be useful (for active users you would normally use the offer function for this, but for inactive users you can not do this). I can also re-use this issue or create a new one, to tackle the problem of packages leaking into other collections, as happened with the Occult RERaise DLC's in the screenshot.

**Comment by Tecfan** [comment]
See also #134 for more filtering weirdness.

**Comment by bartervg** [comment]
I implemented this suggestion as an alternative means of addressing this issue. 
![image](https://user-images.githubusercontent.com/28576132/105636528-cddd2800-5e36-11eb-9907-d0ffe5b56693.png)
