### ISSUE TITLE
Broken hash link

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#216]
## Describe the bug
The link to the trader's steam profile comment has a wrong hash link.

## Steps to reproduce the bug
1. Visit a trade page 
2. Click link on `Next Step: leave feedback for xxx on Steam profile  note 📓`
3. Observe page not being scrolled to comments

## Expected behavior
Steam profile page being scrolled to comments.

### Additional context
Perhaps a better solution would be to link to /allcomments/ instead

**Comment by bartervg** [comment]
When completing an offer with you, I got this link to your Steam profile
https://steamcommunity.com/profiles/76561198042965266#commentthread_Profile_76561198042965266_0_area
That doesn't jump to the comments. `#commentthread_Profile_76561198042965266_area` does work.

However, using that long hash does not seem reliable. /allcomments is far less likely to change and it looks like a better page for this purpose.

I changed the link to https://steamcommunity.com/profiles/76561198042965266/allcomments (link with vary by SteamID64) and the anchor text to `Steam profile comments`. Thank you for the suggestions.
