### ISSUE TITLE
Steam GIF profile image doesn't sync

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#242]
# Describe the bug
Profile images that are gifs do not sync to Barter.vg profiles

## Steps to reproduce the bug
1. Go to https://barter.vg/u/6874/ 
2. See that Barter.vg profile has a ? default profile png image and Steam has a gif
3. Syncing does correct it

## Expected behavior
Barter should use the same profile picture as Steam (even if it is animated?).

### Screenshots
![image](https://user-images.githubusercontent.com/28576132/108604212-846ef280-737a-11eb-887d-f6d3e6363aff.png)

### Additional context, device information (OS & Browser) if applicable 
Reported on Discord https://discord.com/channels/329829406153375755/581243124916158464/812464704856522802

**Comment by bartervg** [comment]
This was due to the Steam API profile sync never having worked. The only reason why it wasn't broken for everyone was that the old wishlist sync still updates profile image and name. This old sync doesn't work for .gif images.

The Steam API hasn't changed. It was a matter of ensuring the Barter.vg server processed it correctly. Unfortunately, it silently failed and returned successful regardless of the results. It should now return `failed` if the results are empty or if the update query fails.
 
![image](https://user-images.githubusercontent.com/28576132/108607232-28fa3000-738d-11eb-8146-002ab1471b45.png) 
Clicking the Sync profile with Steam now button will request a Steam profile API sync which includes image and persona name. This sync is run independently of wishlist and library, and therefore should complete even if the other syncs fail.

**Comment by Revadike** [comment]
Hmm, I have this now:
![image](https://user-images.githubusercontent.com/4411977/108929717-d6e33400-7644-11eb-8072-bf3c400eb9e3.png)

Could be because of the steam tuesday maintenance? But I never had this happen before, I think. So, its either because of this change or steam maintenance. BTW, I have an animated avatar border. Not sure if that affects anything.
