### ISSUE TITLE
Game Pass for PC has broken links

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#246]
# Describe the bug
Item [Game Pass for PC](https://barter.vg/i/106021/) displays a steamdb icon, linking to https://steamdb.info/app//
As well as a broken ITAD link.

## Steps to reproduce the bug
*Trivial*

## Expected behavior
Don't show broken icons.

**Comment by lillje** [comment]
I can't see the SteamDB icon that you mention, does it maybe come from a userscript?

At the moment, ITAD links are generated based on the item title and sometimes that item doesn't exist on ITAD. Any idea how to check if an ITAD link is valid or not?
For example, [Game Pass for PC](https://isthereanydeal.com/game/gamepassforpc/info/) does not exist as an item, but [3 Months Xbox Game Pass for PC](https://isthereanydeal.com/game/iiimonthsxboxgamepassforpc/info/) does.

**Comment by Revadike** [comment]
> I can't see the SteamDB icon that you mention, does it maybe come from a userscript?

I thought I saw it on the item page too, but you can still see it in an offer page, for example: 

> At the moment, ITAD links are generated based on the item title and sometimes that item doesn't exist on ITAD. Any idea how to check if an ITAD link is valid or not?
> For example, [Game Pass for PC](https://isthereanydeal.com/game/gamepassforpc/info/) does not exist as an item, but [3 Months Xbox Game Pass for PC](https://isthereanydeal.com/game/iiimonthsxboxgamepassforpc/info/) does.

Maybe `https://api.isthereanydeal.com/v02/search/search/?key=<APIKEY>&q=<QUERY>`

**Comment by bartervg** [comment]
> I thought I saw it on the item page too, but you can still see it in an offer page, for example: https://barter.vg/u/48e/o/3978877/

![image](https://user-images.githubusercontent.com/28576132/110547358-d004f880-80fd-11eb-982c-e5b9e1fdd57b.png)

> ITAD links are generated based on the item title

At least for Steam apps, the links are based upon https://api.isthereanydeal.com/v01/game/plain/id/?shop=steam&ids=[appids] (itad_plains.php cron)

> but 3 Months Xbox Game Pass for PC does.

I changed the ITAD link on the profile page
![image](https://user-images.githubusercontent.com/28576132/110547514-0a6e9580-80fe-11eb-90a1-fe0716a19d3b.png)

**Comment by Revadike** [comment]
> SteamDB links shouldn't appear for any item that is not appID or subID. If you find an example, try disabling all plugins and reloading the page. If it is still there, (small) bug bounty incoming.

It's gone now, but it was definitely there.

**Comment by bartervg** [comment]
> Steps to reproduce the bug
>
> Trivial 

Less trivial than expected. Next time screenshot it!  
![image](https://user-images.githubusercontent.com/28576132/110623940-8a7f1480-816b-11eb-9c77-c6ebff8852f2.png)



SteamDB links should appear for Steam apps and packages only. It's possible that Game Pass was mistakenly listed as a Steam app, but it appears to be fixed now.
