### ISSUE TITLE
Counter Stats

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#251]
# What problem does this feature address?
Right now, one can only guess whether a trader likes to counter received trade offers, or doesn't bother with them.

## Describe a solution
Display statistics on how many received offers are declined vs countered.
Maybe also display of those countered offers, how much percentage leads into a trade.
This gives more insight how fast traders will give up on crafting a suitable offer between traders. 

## Examples of similar features
Like these other stats
![image](https://user-images.githubusercontent.com/4411977/111984875-392c3900-8b0c-11eb-8657-1e1e018b7dc1.png)

**Comment by bartervg** [comment]
Good point. I thought `countered` may have been excluded or in a separate category, but no, `countered` is the same as any other declined.

I created more stats for each declined reason. The table structure is less than elegant, but let's see if displaying the reason counts in aggregate will be helpful.

**Comment by bartervg** [comment]
The decline stats are on the profile, although there was a naming typo that resulted in the `Already Own` to not count anything. It's recounting, which takes around 30-45 minutes.
Display as number of offers or percent of total declines?
Increase space between the two tables?
Display the site average for context?

**Comment by Revadike** [comment]
It may be too detailed. At least, for a profile page.
How about this:
Make a separate page https://barter.vg/u/48e/stats/ with detailed info of user statistics, with both absolute and relative (%) numbers.
And then just display the really insightful and quick stats about this trader only, like how much percent the trader declines, counters and accepts, with a link to the full statistics page. You could give those percentages a `title` attribute with their absolute numbers. But I really think percentages are easier to understand than just numbers.

**Comment by bartervg** [comment]
New page? Yes, one day, but not today. Instead, I moved Overview to the top and switched the decline count to %. 

That should address the original issue. Future TODO: 
Site average row in order to have a basis for comparison. 
`Other` column so the %s add up to 100% (usually, although not always due to rounding).

**Comment by Revadike** [comment]
There are still a few things confusing to me:

1. I think fulfillment rate needs to go. 99% of the people that see this will have no clue what it means. They'll have to look up what exactly it means. Instead, this should just be given clear info and make judgement based on that.
2. Does items traded consider quantities? If not, it would make sense it will.
3. In statistics you use > and <, but this is not very clear. I think you should just put sender and receiver as row headers. 
4. In statistics you use the  `title` tooltip for some to show the absolute counts. You should do this for every percentage stats.
5. Instead of `-`, just put `No Reason` there.
6. You should right align "Declines" too, like the rest.
7. Ensure that the columns are aligned, to make it more visually pleasing.
