### ISSUE TITLE
Resume button

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#254]
# What problem does this feature address?
There is a pause offer button, but no resume button

## Describe a solution
Add a resume button when the offer is paused

## Examples of similar features
No

**Comment by bartervg** [comment]
The current process to resume is edit and propose. A resume button would eliminate the edit step.

**Comment by bartervg** [comment]
Also needed, resume all offers. The auto pause is too aggressive pausing offers.

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/113510246-f31d9f00-9527-11eb-9d97-807e782a88a5.png)

**Comment by bartervg** [comment]
If the receiver of the offer leaves the page opens, and the sender pauses it, the receiver can accept and there's no indication that the accept failed. Clicking the accept button reports that the offer was accepted regardless of whether the status changes or not.

![image](https://user-images.githubusercontent.com/28576132/113511101-28c48700-952c-11eb-8631-e737485c1e7c.png)

This occurs despite the offer being paused and ignoring any attempts to accept.

**Comment by bartervg** [comment]
A resume bad design problem: the expiration date doesn't update. Therefore someone could pause for 3 days, then resume a few seconds before expiration. 

Resume should extend expiration such that the expiration time is at least as long as the receiver's minimum expiration preference. If the pausers want more control over expiration time, they can edit rather than resume.

**Comment by bartervg** [comment]
> Clicking the accept button reports that the offer was accepted regardless of whether the status changes or not.

![image](https://user-images.githubusercontent.com/28576132/197485361-e02a4f12-c37f-4f78-8227-3e8d58c1614d.png)
[ the sender pauses the offer while the receiver is about to accept offer ] 
![image](https://user-images.githubusercontent.com/28576132/197485415-f114325c-5ad4-4835-9a12-846f0d952316.png)

The offer would not switch to accepted before this change. However, there was UI that would claim offer accepted whenever the button was pressed, regardless of what happened with the database.

**Comment by bartervg** [comment]
> Resume should extend expiration such that the expiration time is at least as long as the receiver's minimum expiration preference.

Upon resume, the expiration is checked to ensure it confirms with the receiver's preference. If now, the expiration is set to equal the minimum number of days that the receiver prefers. If the user doesn't have a preference set, the default is 3 days.

**Comment by Revadike** [comment]
> > Resume should extend expiration such that the expiration time is at least as long as the receiver's minimum expiration preference.
> 
> Upon resume, the expiration is checked to ensure it confirms with the receiver's preference. If now, the expiration is set to equal the minimum number of days that the receiver prefers. If the user doesn't have a preference set, the default is 3 days.

Wouldn't it make more sense to add the amount of time the offer has been paused to the expiration time? So essentially, the expiration "countdown" gets paused too?

**Comment by bartervg** [comment]
> the amount of time the offer has been paused 

This value isn't readily available. All that the offer saves is the unix timestamp of expiration.

**Comment by Revadike** [comment]
expire_unix = expire_unix + (resume_unix - pause_unix)

you should have this data from the offer timeline:
![image](https://user-images.githubusercontent.com/4411977/197565363-f391f97a-fcf6-4b69-a7d4-6ff6bb3fa275.png)

**Comment by bartervg** [comment]
> (resume_unix - pause_unix)

These values are not saved in the offer. Yes, they're in the feed, but the offer doesn't have access to those values. I do have a slight preference towards your approach, but not enough to implement it.
