### ISSUE TITLE
API: profiles that have not sent or received offers return an array of 1 object

### ISSUE THREAD

**Issue by antigravities** [bartervg/barter.vg#257]
# Describe the bug
Profiles that have not sent or received offers return an array of an object through the API endpoint `/u/hexID/o/json`, as opposed to an object with with just a key `0`. This edge case causes potential issues with parsing the response from endpoint as the returned objects are fundamentally different.

[Here is a profile that contains zero offers](https://barter.vg/u/6f75/o/json) (at time of writing), as opposed to [a profile that contains one or more offers](https://barter.vg/u/6f76/o/json).

## Expected behavior
The API should return an an object with with a key `0` if the profile has not sent or received any offers.

**Comment by Revadike** [comment]
I think the 0-key object is annoying to deal with. I'd rather just remove it.

**Comment by bartervg** [comment]
>
> 
> The API should return an an object with with a key `0` if the profile has not sent or received any offers.

Researching...

![image](https://user-images.githubusercontent.com/28576132/113480357-e9316880-9461-11eb-85f2-bcaff52643e7.png)

Knowledge Acquired
https://stackoverflow.com/questions/15290811/php-json-encode-issue-with-array-0-key
```php
$result = json_encode($array, JSON_FORCE_OBJECT);
```

Result
https://barter.vg/u/6f75/o/json 
```json
{"0":{"count":0}}
```

**Comment by bartervg** [comment]
> 
> 
> I think the 0-key object is annoying to deal with. I'd rather just remove it.

Yes, in hindsight, this decision doesn't make much sense. I'll remember it for JSON feed 2.0.

**Comment by antigravities** [comment]
> I think the 0-key object is annoying to deal with. I'd rather just remove it.

I was just aiming for consistency. Breaking changes should be part of a 2.0.
