### ISSUE TITLE
Loot boxes cause the bundle count to be bolded

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#258]
# Describe the bug
On the offer page, a bolded bundle count indicates that there is an active bundle or special with the game. Fanatical loot boxes don't increment the bundle count, but they do cause it be bolded. While in theory, a buyer may be able to acquire the game this way, it isn't a reliable means of doing so and therefore it is misleading.

## Steps to reproduce the bug
1. Go to https://barter.vg/bundle/5431/ and click on an unbundled game
2. Go to the offers section, click on the offers
3. Notice that the bundle count is bold

## Expected behavior
The bundle count should not be bold for loot boxes. It should be bold if there is a bundle or special available for purchase at a known price that includes the game. 

### Screenshots
![image](https://user-images.githubusercontent.com/28576132/113527979-3fe79100-958d-11eb-8c67-aab024a14cd6.png)
![image](https://user-images.githubusercontent.com/28576132/113527988-47a73580-958d-11eb-8899-9dc4a86d0bfa.png)

### Additional context, device information (OS & Browser) if applicable 
Originally thought it was GeForce tracking bundle problem https://discord.com/channels/329829406153375755/438406560222281738/828432913908498493

**Comment by lillje** [comment]
On the contrary, I think you should keep it highlighted. There should be an indication that a game was bundled, even if it comes from a Mystery one. Considering that Mystery bundles are extremely often nowadays and that we see more or less the same games in all Mystery bundles, it makes sense to consider them as bundles as well, even if they don't increment the bundle count. Games that appear in only one Mystery bundle (thus relevant for turning off this feature for them in particular) are extremely rare.

**Comment by bartervg** [comment]
When should the bundle count be displayed in bold?

**Comment by Luckz** [comment]
Bold implying "you can mouse-over this for more information via the alt text" seems like user-friendly design. Making it not bold only removes that hint at further information.
_Bold = haz alt text_?

#NotABug   😸

**Comment by bartervg** [comment]
The bundle count has a title attribute in nearly every case, even if it is 0 bundles. Currently, there's no connection between bold and whether placing the cursor on the bundle count displays any text. 

Mortal Kombat X has 0 bundle count, 13 specials, but no ongoing bundles or specials and therefore is not bold, but place cursor on the bundle count and it displays the 13 specials,
![image](https://user-images.githubusercontent.com/28576132/113598371-06ee0180-960b-11eb-8fc7-bcc06becf900.png)
(The original issue was should GeForce cause the bundle count to be bold, but it doesn't. The next question is should GeForce appear as a special?)

Bundle count of 9 and at least 1 bundle or special is ongoing, in that the bundle is listed as ongoing. In this case, DIG Weekly Bundle 413.
![image](https://user-images.githubusercontent.com/28576132/113596210-f8521b00-9607-11eb-9281-4323a5350e73.png)

Whereas this count is not bold, but still displays all the bundles. It is not bold because it is not in an ongoing bundle. It hasn't been one since 2019.
![image](https://user-images.githubusercontent.com/28576132/113596504-6ac2fb00-9608-11eb-8f19-0377a20d30a3.png)

This is true with the giveaway icon as well. The intent was for bold to indicate that there's an ongoing option rather than only those that ended.

**Comment by lillje** [comment]
Only Pick & Mixes / Store deals / Mystery should be marked as Special. The idea behind "Special" is that you can trade the games from it, but they don't count as "bundles" because of the high price.
Since tracking bundles and subscription bundles aren't meant for trading, they shouldn't be considered "Special".

> should GeForce cause the bundle count to be bold?

No.

> The bundle count should not be bold for loot boxes.

Indeed, but lootboxes are / should be "Special" and that complicates things.
We could have a new type of bundle, called "Lootbox" - similar to Subscription and Tracking: not included in bundle count, not considered for bold-ing the count.
All Mystery bundles and some of the GMG bundles will need to be moved from "Special" to this new type.

**Comment by bartervg** [comment]
Added `loot box` as bundle type. https://barter.vg/bundle/5403/ 

Unfortunately, it's hard coded in one place, but otherwise it is a single row added to bundles_types

**Comment by bartervg** [comment]
To address the other issue. If the bundle count is 0, but there are other things to list the bundle count could include * or + like the bundle charts. However, `0*✽` looks strange.

The standard styling for the abbr is a dotted underline. ![image](https://user-images.githubusercontent.com/28576132/113797560-810faa80-971f-11eb-9488-13c7896709be.png)

Bold = available to acquire now in a bundle; dotted underline = view non-empty list in a tooltip?

**Comment by bartervg** [comment]
I assume this is working as expected. 
![image](https://user-images.githubusercontent.com/28576132/197509630-d0e06ea5-5289-4931-aa8c-5333dbd7c6f0.png)

Closing as 
> #NotABug 😸
