### ISSUE TITLE
Offer API does not use the passed `user_id` at all

### ISSUE THREAD

**Issue by osmanyucel** [bartervg/barter.vg#266]
# Describe the bug
While calling the offer API, as long as you pass `offer_id` correctly, it doesn't matter what user ID you pass.

## Steps to reproduce the bug
1. Go to https://barter.vg/u/a4/o/1168888/json/
2. See that even though `user_id` passed is `a4` the offer has nothing to do with that user. 

## Expected behavior
It should work as either one of the following options:
- User should not have to pass a `user_id` while calling this API. (My personal preference is this, because it makes the API much easier to use) 
- If the `order_id` and `user_id` doesn't match, the API should return an error message. 

### Screenshots
![Screenshot from 2021-04-19 00-25-43](https://user-images.githubusercontent.com/5606952/115197494-e52e5900-a0a5-11eb-85d3-a96449abe0a4.png)

**Comment by bartervg** [comment]
Is this a bug or a feature? I won't change anything, at least until you've finished.

**Comment by Revadike** [comment]
It's unexpected behavior, but likely to be desired.
Something to keep in mind for designing API v2. 

@osmanyucel want to help document the current API?
https://github.com/bartervg/barter.vg/wiki

**Comment by Revadike** [comment]
We could have a wiki page to list all current bugs and bad design issues, like this one. And consider them for API v2.

**Comment by osmanyucel** [comment]
> It's unexpected behavior, but likely to be desired.
> Something to keep in mind for designing API v2.
> 
> @osmanyucel want to help document the current API?
> https://github.com/bartervg/barter.vg/wiki

> We could have a wiki page to list all current bugs and bad design issues, like this one. And consider them for API v2.

I don't think I can find the time to work on the documentation, but I can list the design issues I see with the current API and share with you.  I wasn't going to bring it up but if you have an API v2 on the horizon already, I can share my opinions about the API design.

**Comment by Revadike** [comment]
I'm not working on API v2. That would be done by @bartervg, but I don't think he started.

Also, I don't think this is the place to discuss all current API flaws, unless we convert this issue to it.

**Comment by bartervg** [comment]
https://barter.vg/u/a4/o/1168888/json/

> {"offer_id":1168888,"success":false,"error":"this offer is not associated with the user"}

https://barter.vg/u/11dc/o/1168888/json/

> {"offer_id":1168888,"success":true,"from_user_id":"11dc" ... }

**Comment by Revadike** [comment]
that may be a breaking change
