### ISSUE TITLE
Offer RSS feed - HTTP Error 500

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#269]
# Describe the bug
Sometimes when I load https://bartervg.com/u/48e/o/rss/, I get HTTP Error 500.

## Steps to reproduce the bug
1. Go to this URL: https://bartervg.com/u/48e/o/rss/
2. Observe HTTP Error 500 (if not, refresh)

## Expected behavior
Always working

### Screenshots
![image](https://user-images.githubusercontent.com/4411977/116004761-8700f900-a604-11eb-878b-9374eb403302.png)

### Additional context, device information (OS & Browser) if applicable 
Windows 10 x64
Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

**Comment by bartervg** [comment]
memory exhausted error
long-term fix: improved efficiency
short-term fix: increased memory

https://bartervg.com/u/48e/o/rss/ ✓ 200
