### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#270]
# Describe the bug
Some barter item images are broken

## Example
See here https://barter.vg/u/48e/o/4058858/

## Expected behavior
1) Have a proper `alt` attribute
2) Make use of the `onerror` attribute and make it load a default image when the external image cannot be loaded. 
For steam games this could be:
![](https://steamdb.info/static/img/applogo.svg)

### Screenshots
![image](https://user-images.githubusercontent.com/4411977/116138891-ae73c680-a6d5-11eb-8826-d8e6f79ec242.png)

**Comment by Revadike** [comment]
So, you can implement it like this:
https://jsfiddle.net/oLqfxjoz/

**Comment by bartervg** [comment]
Implemented on bundle page, 
https://barter.vg/bundle/1116/ 
Different implementation on item profile page, 
https://barter.vg/i/47283/

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/116835057-ce503200-ab8e-11eb-94cd-22b00b47cd16.png) 🤨 😩

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/116835107-59e2b680-abc1-11eb-9832-24fd841101f9.png)

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/117064664-76cbd680-acf4-11eb-8b5c-f634163bcb8e.png)

**Comment by Revadike** [comment]
Perfect, but the item page is still broken for me.

**Comment by bartervg** [comment]
I changed item profiles to a similar style as bundles and offers.

![image](https://user-images.githubusercontent.com/28576132/117066158-63ba0600-acf6-11eb-8055-f3d4c46a849e.png)

**Comment by Revadike** [comment]
You can still see the broken img icon, and isn't no-repeat better?

```css
    background-size: contain;
    background-repeat: no-repeat;
    background-color: #171a21;
  
  ```
![image](https://user-images.githubusercontent.com/4411977/117066922-a517d900-ad29-11eb-952c-3c5678d1a426.png)

**Comment by bartervg** [comment]
I believe to hide the broken image icon, the `img::before` hack should be used instead. Also, to avoid the low resolution blurry look, it would require a different image.

**Comment by Revadike** [comment]
> I believe to hide the broken image icon, the `img::before` hack should be used instead.

That method doesn't replace the broken image, this method does: https://jsfiddle.net/oLqfxjoz/

**Comment by bartervg** [comment]
By replace, I assume you mean don't display the broken image icon, ![image](https://user-images.githubusercontent.com/28576132/117085987-519d8f00-ad19-11eb-89f5-dc41f908483c.png)

I added 
```css
.cover::before { 
    content: ' ';
    display: block;
    position: absolute;
    height: 215px;
    width: 460px;
    background-image: url(https://bartervg.com/imgs/ico/steam184_69.png); 
}
```
which accomplishes hiding the broken image. I'm not fond of the repeating Steam logos, but also not in a rush to create a big Steam logo.

**Comment by Revadike** [comment]
> By replace, I assume you mean don't display the broken image icon, ![image](https://user-images.githubusercontent.com/28576132/117085987-519d8f00-ad19-11eb-89f5-dc41f908483c.png)

no, with replace I mean actually replace. Did you see the code snippet I linked? It replaces the `src` attribute of the image `onerror`. When replaced you will indeed not see any broken image anymore.



> but also not in a rush to create a big Steam logo.

You could use a svg image. I think it stays clear no matter what size. https://steamdb.info/static/img/applogo.svg

**Comment by Revadike** [comment]
Seems animated avatars on steam also display broken images:
https://barter.vg/u/70a3/
![image](https://user-images.githubusercontent.com/4411977/117144384-26b34980-adb2-11eb-8a0b-32dd7e63048e.png)

**Comment by bartervg** [comment]
> Seems animated avatars on steam also display broken images:

This was a different issue, but more important than the missing item images. It was related to https://github.com/bartervg/barter.vg/issues/242 but for new users. The onboarding process did not correctly sync profiles, same mistake as described in #242
