### ISSUE TITLE
Do not own base game - decline reason

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#271]
# What problem does this feature address?
The current decline reasons seem to be only tailed for games, but what about other items, like DLC. I'd like to decline a DLC offer for not owning the base game (perhaps also make this an offer preference, but that's another issue). 

## Describe a solution
Add "Do not own base game", or more general "Do not have required item(s)" as decline reason.

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/196926202-b3d81a8b-5a12-4419-84c4-dd9336ceddf6.png)
