### ISSUE TITLE
Bug with counting x0 tradables in offers

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#275]
# Describe the bug

Something is wrong with the counting of x0 tradables in the offers. See here, x3 tradables + x0 tradable:

![image](https://user-images.githubusercontent.com/956878/122006956-bf78b400-cdb7-11eb-98c1-f7323d2de33b.png)

This leads to a weird: "tradable x0 x3, x0, blacklist" (double "x0" even though it's just one x0):

![image](https://user-images.githubusercontent.com/956878/122007033-d3bcb100-cdb7-11eb-864f-f8c6c2016189.png)

Removing the x0 tradable, goes back to x3, both x0's disappear:

![image](https://user-images.githubusercontent.com/956878/122007091-e2a36380-cdb7-11eb-9d28-3488e6eb5588.png)

## Steps to reproduce the bug
1. Copy the setup in my screenshots

## Expected behavior
"x3, x0" not "x0, x3, x0"

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/196914438-e2b924c0-a2c0-4137-afb7-c9f27cdd731d.png)
