### ISSUE TITLE
Can't comment on multi-user offer unless using own URL

### ISSUE THREAD

**Issue by Luckz** [bartervg/barter.vg#277]
# Describe the issue
There's an automatic redirect when trying to view a trade with you as another user. Shouldn't there be the same for multi-user offers?

## Steps to reproduce
1. I go to https://barter.vg/u/644a/o/4123496/
2. I can't post a comment

## Works this way
1. I go to https://barter.vg/u/427/o/4123496/
2. I can post a comment

**Comment by bartervg** [comment]
Multiuser offer will redirect to the viewing user's offer page.
