### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#278]
![image](https://user-images.githubusercontent.com/4411977/125214643-77ff1e00-e2b8-11eb-8db1-52f7a8002b4e.png)

https://barter.vg/list/?

It should be `variables`

**Comment by bartervg** [comment]
var·i·a·ble ✓

![image](https://user-images.githubusercontent.com/28576132/129492156-622b792a-bb8c-4514-b0e4-38ecff76757b.png)
