### ISSUE TITLE
Automatically cancel pending offers, when item already received

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#28]
Similar to https://github.com/bartervg/barter.vg/issues/9, this would cancel trade offers, or remove items from existing trade offers, if another offer with a common picked item gets accepted. Of course, this should be optional and perhaps added as an option when a trade gets accepted. This would make https://github.com/bartervg/barter.vg/issues/27 unnecessary.

**Comment by bartervg** [comment]
The solution for #9 should work for both incoming and outgoing tradables in pending offers,

**Comment by Revadike** [comment]
This issue is being covered by #9. Closing this.
