### ISSUE TITLE
`Bold, counteroffer encouraged` enhancement

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#280]
When setting `Bold, counteroffer encouraged` it often goes ignored. I'm proposing when this is set, and the counter-trader clicks decline offer, they will first get a prompt that the sender encourages a counter offer.

**Comment by bartervg** [comment]
`encouraged` not `mandated`
I know there are many UI problems on the site, but I think the problem is more fundamental here.

**Comment by Revadike** [comment]
So here's my problem. I wish more people would counter offers. It's rare for offers to be perfect the first time you send them. More often than not, an offer gets declined and then afterwards we chat or send a new offer to come to a compromise.

**Comment by bartervg** [comment]
I don't think a series of popups would replicate your chat negotiation skills. Perhaps, one day we could feed all your Steam chats into a language model, but that's out of scope at this time.
