### ISSUE TITLE
Demand a decline reason

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#281]
# What problem does this feature address?
When an offer goes declined, it is often without any reason. Then, I often have no idea what to do to make the offer more attractive for the other user. I have to ask manually, which is suboptimal. 

## Describe a solution
Just like users can set their min expire time, allow us an option to demand a decline reason. Additionally, add a decline reason `Not interested, do not want a counter`. 

## Examples of similar features
Kinda like the minimum expire time option.

**Comment by Luckz** [comment]
Do you think it should be mandatory that you include a two sentence or longer essay explaining why you think your own offer is fair, balanced, and should be accepted? I'm sure if you do that, you'll get more decline explanations too.

**Comment by Revadike** [comment]
It doesn't affect the number of decline explanations, I tried.

**Comment by antigravities** [comment]
I don't understand how declining without a reason doesn't implicitly state "not interested, do not want to counter."

**Comment by Revadike** [comment]
The difference is that traders much manually pick that.

**Comment by antigravities** [comment]
That doesn't really answer my question. If someone is not interested in the trade and does not want to counter the offer, they'll just... decline and not counter. Why does that need to be a separate decline reason?

And either way, if someone is "forced" to specify a reason, what's stopping them from selecting a reason that's inaccurate just because they have to select a reason?

This idea doesn't seem like it would generate the kinds of data you're expecting in an accurate manner.

**Comment by bartervg** [comment]
> Do you think it should be mandatory that you include a two sentence or longer essay explaining why you think your own offer is fair, balanced, and should be accepted?

This is a good point that may be overlooked as snark. Given that your offers could be automated and that you've sent 10x more offers than you've received, you'd (or any other senders) have the ability to create even more work for others at no extra effort to yourself. It would be nice to know what the offer recipients think, but there should be no obligation. 

Personal aside, I dislike when companies "nudge" / force me into providing feedback, especially when cancelling. In addition, when I looked at offer pages recently, it was distressing. There look to be too many offers, and slowing down the time it takes to go through them would make it even more unpleasant. 

> And either way, if someone is "forced" to specify a reason, what's stopping them from selecting a reason that's inaccurate just because they have to select a reason?

I agree. Forced feedback would generate noise. At least now, you have some confidence that the reasons you do receive are accurate.

**Comment by Revadike** [comment]
So, I've been thinking about this. I still it's a good idea. How is it any different to "forcing" expire time, or other offer options? As for the noise argument. At first, this seemed valid, but then I figured it would only disadvantage themselves, if they choose the wrong feedback option. Because it will cause the sender to act incorrectly in response to the incorrect feedback. Therefore, the incentive would be to pick the correct feedback. Finally, declining without a reason does not implicitly state "not interested, do not want to counter.", instead it simply means that the user forgot or did not see the value in stating a decline reason.

**Comment by bartervg** [comment]
> did not see the value in stating a decline reason.

Yes, exactly. If the choice is forced and they do not see the value, then you will receive the easiest option to select. You will increase noise. Would you rely on the age check information for accurate demographics? (wow, a lot of 122 year olds on Steam!)

It seems like you've stumbled upon the better solution. Explain the value of decline reasons. It won't lead to 100% response rates, but it will lead to more accurate feedback.
