### ISSUE TITLE
Paused offers expire after a few days

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#283]
# Describe the bug
Paused offers seem to expire after a few days without any indication that they're going to expire. 

## Steps to reproduce the bug
1. Pause an offer
2. Wait

## Expected behavior
Don't expire, or show when they expire.

**Comment by bartervg** [comment]
Receiver sees:
> Next Step: wait for sender to propose or cancel offer; otherwise, offer automatically cancels in 3 days

Sender sees:
> Next Step: edit or cancel this offer; if you do nothing, this offer will cancel in 3 days

Added the text `in 3 days`

**Comment by Revadike** [comment]
Why do paused offers expire?

**Comment by bartervg** [comment]
Same reason editing and creating offers expire. Collections change, offers become stale. In addition, many users don't like seeing offers they can't accept or decline stuck on their offer page.

**Comment by Revadike** [comment]
> Same reason editing and creating offers expire. Collections change, offers become stale. In addition, many users don't like seeing offers they can't accept or decline stuck on their offer page.

![image](https://user-images.githubusercontent.com/4411977/200680466-f1c737da-5fe9-4e45-9500-003b6f935eec.png)

**Comment by bartervg** [comment]
I'm struggling to comprehend the screenshot conversation. LuckyStrike1305 doesn't want paused offers to expire?

**Comment by Revadike** [comment]
> I'm struggling to comprehend the screenshot conversation. LuckyStrike1305 doesn't want paused offers to expire?

Yes
I also don't really understand him, but he seems annoyed
