### ISSUE TITLE
Track Steam Family Sharing excluded apps

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#284]
# What problem does this feature address?
Steam Family Sharing excluded (`exfgls`) games may be more valuable to people, because they cannot be obtained from other people libraries.

## Describe a solution
Track this property

## Examples of similar features
https://steamdb.info/search/?a=app_keynames&type=-1&keyname=261&operator=3&keyvalue=1

**Comment by Luckz** [comment]
How would we? Can't scrape that from the store AFAIK, SteamDB keeps info to themselves.

**Comment by Revadike** [comment]
requesting product info

**Comment by bartervg** [comment]
Easily accessible URL for this info?

**Comment by Revadike** [comment]
> Easily accessible URL for this info?

`app_info_print <APPID>` in steam console.
If you want to implement via backend, I suggest using https://github.com/xPaw/SteamWebPipes/

**Comment by bartervg** [comment]
> `app_info_print <APPID>` in steam console. 

What's the workflow for this? I open Steam console, type `app_info_print <APPID>` a hundred thousand times, and transfer the results to the site?

> If you want to implement via backend,

If you want to implement it, I would greatly appreciate a feed and I'm sure other users would appreciate it.

**Comment by Revadike** [comment]
> If you want to implement it, I would greatly appreciate a feed and I'm sure other users would appreciate it.

I maintain a database together with a different community. I don't think they'll like it very much, but I'll see what I can do.

**Comment by Revadike** [comment]
> What's the workflow for this? I open Steam console, type app_info_print <APPID> a hundred thousand times, and transfer the results to the site?

Use the project I linked. Or make some custom implementation via SteamKit yourself.

**Comment by bartervg** [comment]
> Or make some custom implementation via SteamKit yourself.

The usefulness:effort ratio isn't high enough, especially if you already have the data elsewhere.

**Comment by bartervg** [comment]
You called my bluff. Well played. I hope your source doesn't mind 90k requests.
https://barter.vg/browse/tag/647/
bonus https://barter.vg/browse/tag/648/

**Comment by bartervg** [comment]
Revadike was kind enough to share a data source with exfgls. Also, it has Steam Deck compatibility categories. 

There are 86197 Steam games in the database, so at 1 request per second, it will take around a day to check them all.

**Comment by Revadike** [comment]
Thanks for implementing it so quickly!

**Comment by bartervg** [comment]
All items checked. 24823 games where `exfgls` = 1. @Revadike does that look accurate?

2399 Steam Deck Verified, 3662 Steam Deck Supported, 2206 Steam Deck Unsupported, Steam Deck Unknown 0 (either I didn't do this correctly or this tag doesn't exist)

**Comment by Revadike** [comment]
https://store.steampowered.com/search?deck_compatibility=3

https://store.steampowered.com/search?deck_compatibility=2

**Comment by bartervg** [comment]
https://store.steampowered.com/search?deck_compatibility=3 
Steam Deck Verified: 2365 results filtered by game (2989 total)
That's 34 fewer than Barter. On Barter, of the 2399, looks like there are 44 delisted+banned+purchase disabled games. 

https://store.steampowered.com/search?deck_compatibility=2
Steam Deck Supported: 3583 games (4492 results)
79 fewer than Barter. Close enough? 

Thanks again for the feed.
