### ISSUE TITLE
Counter attempted

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#285]
# What problem does this feature address?
When an offer gets declined, I don't know if the person attempted a counter or not. So, I don't know whether to suggest the person to counter.

## Describe a solution
Add a button after pressing counter that says: "Unable to counter". The people who don't want to counter or are too lazy, will not bother clicking 2 buttons on 2 pages and simply directly decline, while people who want to try to counter will first have to see the "new offer" page, before deciding "Unable to counter".

**Comment by bartervg** [comment]
> When an offer gets declined, I don't know if the person attempted a counter or not.

You should know now.

When someone click the `< Counter` button, you'll see the activity in the offer notifications. I believe this addresses the issue without another button.

**Comment by Revadike** [comment]
> > When an offer gets declined, I don't know if the person attempted a counter or not.
> 
> You should know now.
> 
> When someone click the `< Counter` button, you'll see the activity in the offer notifications. I believe this addresses the issue without another button.

Thank you!
