### ISSUE TITLE
Add the ability to create "AND / OR" trades

### ISSUE THREAD

**Issue by BanicaTom** [bartervg/barter.vg#286]
# What problem does this feature address?

Several times I have wanted to create a trade in which I offer GAME_A...  and additionally a selection from several other games (GAME_B, GAME_C, GAME_D, etc.  

I don't believe this is currently possible on barter.  So I make a trade for a selection from several games. Then I add a comment for the recipient to make a counter offer for whichever game(s) from the selection I offered and then include GAME_A in his counter offer.  That way the recipient can select the games desired and I can be certain that GAME_A (typically a lower cost item thrown in as a deal sweetener) gets selected.

## Describe a solution

Add a second (distinct) set of games to the create trade mechanism.  This structure would be an **exact** replica of the existing set of games... but with the ability to select **both** sets... so the existing structure is:

`User1 sends [number of games] of [list of games] to User2`

This would add a second set of games:

```
User1 sends [number of games] of [list of games] to User2

**AND**

User1 (also) sends [number of games] of [list of games] to User2
```
This would allow the particular trades I would typically offer but would additionally allow the "sweetener" to be a selection of lesser games than the primary games being offered in offer set 1.

Note, if the connector between the 2 sets could be either "And" or "Or", then a user could essentially offer two different offers within the same trade.

**Comment by Revadike** [comment]
Pretty much
https://github.com/bartervg/barter.vg/issues/16
https://github.com/bartervg/barter.vg/issues/17

**Comment by BanicaTom** [comment]
Yes, you are absolutely correct.  

And I know you have better things to do than to show users that their great "new" thought is already "in the works".  I sincerely apologize for not finding at least one of those first.  I try to not be a person who leaps before looking. 

Thank you for taking the time and may you have a wonderful rest of your day/evening/night
