### ISSUE TITLE
Unreadable specific text/link in the footer

### ISSUE THREAD

**Issue by KenChenRyan** [bartervg/barter.vg#287]
# Describe the bug
Second to last row in the bottom of the page (the footer) has unreadable text.

## Steps to reproduce the bug
Go to the homepage barter.vg and you will find it at the bottom 

## Expected behavior
The second to bottom line/link should have readable text but it does not

### Screenshots

![A5EB5126-9064-4438-A9F1-52B634078724](https://user-images.githubusercontent.com/15711645/171161405-abb23513-aadf-49e4-ad05-061220f518c7.jpeg)

### Additional context, device information (OS & Browser) if applicable 
Safari, iOS 14.2

**Comment by Tecfan** [comment]
It's https://emojipedia.org/pocket-calculator/

**Comment by Revadike** [comment]
https://github.com/bartervg/barter.vg/issues/273
