### ISSUE TITLE
Rename platforms

### ISSUE THREAD

**Issue by arseny92** [bartervg/barter.vg#297]
Origin -> EA and icon change
Uplay is still on search results, also with the old Uplay logo

<img width="316" alt="image" src="https://user-images.githubusercontent.com/13212955/200967313-e33da0a1-7e61-4282-a88e-813a797773b2.png">

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/201491711-2554ddfa-5dad-4783-be29-f2893f2eed46.png)
