### ISSUE TITLE
Barter friend list should be private by default

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#305]
# What problem does this feature address?
The friend list on Barter is public by default for every user. There is no option to change this. 
![image](https://user-images.githubusercontent.com/28576132/208776346-cda0196c-3c5b-4779-b3af-91272e4eb753.png)

## Describe a solution
There could be a preference and it would be default private.

## Examples of similar features
User availability is off by default and the user must turn it on to begin trading.

**Comment by bartervg** [comment]
Report by Tylarion on Discord

**Comment by lillje** [comment]
This seems to be a privacy leak.
Likely the issue is that the friends list is loaded based on the id of the user whose collection you are visiting and not on your own id. Fixing this should hide everyone's friends list by default (apart from your own), without needing any extra customizations on the settings page.

**Comment by bartervg** [comment]
At the time of adding the filter, I hadn't considered the friend list to be private information. However, I can see how it looks like a leak since almost all sites have an option to hide friends now.  

The quickest fix was to set it to display the signed in user's friend list, and display nothing if not signed in. I believe that change addresses the issue on the filter collection pages. The function `friends()` appears there only, but it's possible there are similarly designed functions that display friends based on the profile currently viewing rather than the signed in user.
