### ISSUE TITLE
Delete/rename lists

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#31]
Add an option to delete or rename created lists, as suggested by zxcbgt2.

**Comment by bartervg** [comment]
Link to suggestion <https://discordapp.com/channels/329829406153375755/438406560222281738/636150502735740928>

**Comment by bartervg** [comment]
Added Remove List option to https://barter.vg/list/ 
![image](https://user-images.githubusercontent.com/28576132/71842937-cb275d80-3090-11ea-9332-098f12b08a61.png)
