### ISSUE TITLE
Show developer(s) and publisher(s)

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#33]
Show developer(s) and publisher(s) on game pages, as this information can contribute to a game's worth.

**Comment by bartervg** [comment]
Added developer and publisher on game pages. There are several bugs,
- I neglected to add a unique index to prevent identical credits, https://barter.vg/i/1/
- It doesn't update / remove credits, https://barter.vg/i/35547/ 
- Steam doesn't (publicly) assign unique IDs, so there will be incorrect merges of credits, (didn't find an example yet)

Previously, I avoided adding this info until I fixed the problems, but now I set it to visible for long-time users (100+ completed offers).

**Comment by Tecfan** [comment]
I haven't ran into any problems with this so far. Wouldn't it be better to open the function up for all users, but add a warning to the top of the page about the known bugs?

**Comment by bartervg** [comment]
I forgot that developers and publishers aren't being shown to non-signed-in users (anyone without a completed offer). I turned it on for everyone, but left the "noindex" meta tag on the studio pages.

There remains a significant bug, but hopefully limited impact, where previously listed developers and publishers are not removed from the profile page. This is a frequent bad habit of mine: easy to add new data, difficult to update and remove existing data.

**Comment by Luckz** [comment]
SteamDB *removes* the dev and pub when a game is banned. It's **horrible**.
There could be special markdown for dev and pub strings that are not current anymore, but don't wipe them from the database automatically!

**Comment by Revadike** [comment]
> This is a frequent bad habit of mine: easy to add new data, difficult to update and remove existing data.
Perhaps worthy for a separate issue. Perhaps add another cronjob that updates your database ever so often by checking each app in the database.

**Comment by Revadike** [comment]
> SteamDB _removes_ the dev and pub when a game is banned. It's **horrible**.
> There could be special markdown for dev and pub strings that are not current anymore, but don't wipe them from the database automatically!

Odd. Meanwhile, it does remember old/previous app names. I'll bring this up to xPaw, perhaps it's an easy change.

**Comment by Luckz** [comment]
> > SteamDB _removes_ the dev and pub when a game is banned. It's **horrible**.
> > There could be special markdown for dev and pub strings that are not current anymore, but don't wipe them from the database automatically!
> 
> Odd. Meanwhile, it does remember old/previous app names. I'll bring this up to xPaw, perhaps it's an easy change.

While you're at it,

- could sale history of removed titles be preserved nicely? I know it can be reached under the individual subs, that's not terrible.

- https://twitter.com/gluecks/status/1347361854797000704

**Comment by bartervg** [comment]
> Perhaps worthy for a separate issue. Perhaps add another cronjob that updates your database ever so often by checking each app in the database.

"difficult" was an overstatement. Rather than 1 insert query, it needs some loops and UPDATEs (not DELETEs!) so that the old data isn't visible, or it's labeled as former / previous

**Comment by Revadike** [comment]
@bartervg Another page were I'd like to see this implemented is on the browse page. I'd like to see the following:
 * Filters to search for items from a specific developer/publisher
 * Option to show a column with developer/publisher information

I'm thinking, you could implement optional columns like this:
![image](https://user-images.githubusercontent.com/4411977/111219401-44e1a200-85d8-11eb-9f7d-873ef815aaa8.png)
![image](https://user-images.githubusercontent.com/4411977/111219414-49a65600-85d8-11eb-8a15-50737cf757d1.png)
