### ISSUE TITLE
Incorrect Barter Item Information

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#4]
Report here any information of barter items that may be incorrect or missing

**Comment by Revadike** [comment]
https://barter.vg/i/19366/: `item_type` should be DLC (check steamdb)

**Comment by bartervg** [comment]
Steam web API classifies Call of Duty: Black Ops III - Multiplayer Starter Pack as a 'Game' 
https://store.steampowered.com/api/appdetails?appids=437350

The store page is consistent with other 'Game' layouts. There is no warning that a base game is required, no purple DLC banner and no downloadable content category in the right column.

There are many other app type discrepancies (10000+) between SteamDB and Steam API, and common sense and Steam API. The App Type Working Group is conducting an extensive investigation that will become the basis for a white paper.

**Comment by bartervg** [comment]
There are so many type issues, reporting each one here seems Sisyphean. I posted the Steam type information at https://github.com/bartervg/barter.vg/blob/develop/data/items_types.csv that should make it easier to compare.
