### ISSUE TITLE
👥︎ myself

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#47]
**Describe the bug**
Barter.vg thinks I'm friends with myself.

**Steps to reproduce the bug**
Create an offer

**Expected behavior**
Not show friends icon

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/4411977/71767245-71952680-2f0a-11ea-832b-a4ff896988f6.png)

**Comment by Revadike** [comment]
Also https://barter.vg/u/friends/ doesn't include me, or the person I'm sending my offer to.

**Comment by Revadike** [comment]
Should I also mention the placement of that icon is very ugly? Not even a margin between the icon and number of received offers.

**Comment by bartervg** [comment]
👥︎ icon should not appear in that section. It was due to a typo and / or logical error identifying the viewer as either the sender or receiver.
