### ISSUE TITLE
More collection filters

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#48]
**Describe the problem that this feature would improve**
I wanna filter out DLC or games without cards, but I can't. 

**Describe the solution you'd like**
Filter collections (including tradables in offer creation) by hiding or only show the following properties:
 - Item type (DLC, game, etc)
 - Source
 - Form (key, gift, link)
 - Steam limited
 - Cards
 - Bundled
 - Free
 - User tags (alpha / beta)

**Examples of similar solutions**
For GitHub, an example is the filters present on https://github.com/bartervg/barter.vg/issues (Author  Label  Projects  Milestones  Assignee  Sort)

**Comment by bartervg** [comment]
#12

**Comment by Revadike** [comment]
> #12

I was searching for this, but searching for `filter` didn't reveal it.

**Comment by Tecfan** [comment]
I have been looking for a way to filter out games with cards myself. Support this suggestion, and #12.

**Comment by Revadike** [comment]
Closing this, since it's a dupe of #12
