### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#50]
**Describe the problem that this feature would improve**
Comments are limited to plaintext. Supporting markdown would allow for styling and links.

**Describe the solution you'd like**
Start with markdown support for the notes for bundles and giveaways.

**Examples of similar solutions**
Github (this feature request), Steamgifts, Discord

**Comment by Revadike** [comment]
I know barter doesn't like scripts, but I suggest you implement an existing solution/library. Not only will this be easier than building one from scratch, it will also be fully featured and simply better.

**Comment by bartervg** [comment]
Sure, which libraries would you recommend?

**Comment by Revadike** [comment]
Well, I haven't compared them all. I only really worked with https://quilljs.com/ before. It's not really markdown though. It does provides the features of a rich text editor. That said, I do see the appeal of markdown.

**Comment by bartervg** [comment]
I'm trying https://github.com/erusev/parsedown

**Comment by bartervg** [comment]
Added Parsedown to giveaways and bundles 
https://barter.vg/bundle/4659/ 
https://barter.vg/giveaway/5215/
