### ISSUE TITLE
Choose and add a license

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#55]
**Describe the problem that this feature would improve**
Code on this repo is without any license. Without proper licensing, an ignored and disgruntled contributor could file a DMCA complaint against the site.

**Describe the solution you'd like**
List possible license options, choose one, and add it.

**Examples of similar solutions**
https://github.com/erusev/parsedown/blob/master/LICENSE.txt

**Comment by Revadike** [comment]
I usually go for the standard MIT one, but in this case, I think it would be wise to check whether there is a more fitting one.

**Comment by bartervg** [comment]
What attributes would a more fitting license have?

**Comment by bartervg** [comment]
https://en.wikipedia.org/wiki/Software_license 
Copyright retained
Right to copy
Right to modify
Right to distribute
Right to sublicense

It looks like the major differences would be with right to distribute and sublicense.  
https://choosealicense.com/
I'm not sure it makes sense to find a more fitting option that isn't one of the major choices such as MIT, Apache or GPL. Of those, MIT seems like the best fit. If it isn't a good fit, another license is needed, or the code is needed for another project, MIT is flexible to being incorporated into a different license.

**Comment by Revadike** [comment]
close

**Comment by Revadike** [comment]
This issue can be closed as you added a license to the project.
