### ISSUE TITLE
Track whether Steam items appear in API, library, or rgOwnedApps

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#65]
**Describe the problem that this feature would improve**
It's difficult to troubleshoot syncing problems. It would help to know if a particular item like DLC appears in rgOwnedApps only, in which comprehensive sync is required, or if it appears in API or library page, in which an automatic sync should suffice.

**Describe the solution you'd like**
New attributes (api, community, userdata) that update based upon syncing activity

**Examples of similar solutions**
Checked SteamDB and was unsure if this is an attribute.

**Comment by bartervg** [comment]
I believe this has been implemented with `sync-community` and `sync-api`. I added `userdata` as another type and users can set this type by click the `Adding userdata` checkbox 
![image](https://user-images.githubusercontent.com/28576132/105898840-eb9dbf00-5fe7-11eb-8c87-d69842d26fa2.png)
Knowing that an Add IDs addition is based on userdata can lead to other useful features, such as removing previous userdata entries that don't appear in the more recent add.

**Comment by bartervg** [comment]
TODO: pick an icon for the userdata sync type. 
✴ = custom
↷ = sync
`+` = extra (a subset of custom)

**Comment by arseny92** [comment]
Overwrite the `custom` type with `userdata` when adding existing library items with that option ticked.

As well `Paste JSON import format`. need also `userdata import format` due to fields mismatch, to directly paste the userdata JSON and differentiate `rgOwnedPackages`, `rgOwnedApps`. The tick for `Adding userdata (comprehensive sync)` is only available on by raw `ID` input

**Comment by bartervg** [comment]
> Overwrite the custom type with userdata when adding existing library items with that option ticked.

It doesn't do that now, it doesn't modify anything that already exists in the collection, but yes, that would be useful. 

> As well Paste JSON import format. need also userdata import format

The JSON should be for Barter collection rather than Steam userdata imports. 

Although there aren't consequences to labeling an input as custom or userdata now, one feature request is that a userdata sync should remove anything that isn't present in that sync. That would have severe consequences if clicked in the wrong circumstances.

**Comment by Luckz** [comment]
> other useful features, such as removing previous userdata entries that don't appear in the more recent add.

Yes, please.



> Overwrite the `custom` type with `userdata` when adding existing library items with that option ticked.

Yes, but now we need extra warnings:



> a userdata sync should remove anything that isn't present in that sync. That would have severe consequences if clicked in the wrong circumstances.

Yes, I propose renaming _Adding userdata (comprehensive sync)_ to something like _Replace **all** existing items from userdata (comprehensive sync)_ for the 🚨🚨🚨 effect.

**Comment by Luckz** [comment]
P.S.: do you have a cute idea what you'd like to do about `temporary ownership` app IDs? https://store.steampowered.com/subscriptions/ea and possible future subs.
wanna add yet another formdata field, and give them a spiffy icon, and perhaps the option to not be counted as in-library? or should they ideally not be submitted to library at all, and thus filtered out before? or even sent by the script as not-in-library so they're removed if there's an existing store-sync listing?

**Comment by Luckz** [comment]
P.P.S.: The sync summary (/e/#modified) should list:
- items (apps, subs) converted from custom to userdata <library only>
- items (apps, subs) added since last userdata sync
- items (apps, subs) removed due to not being in newest userdata
- [`temporary ownership` items <library only>]

**Comment by Luckz** [comment]
> TODO: pick an icon for the userdata sync type.
> ✴ = custom
> ↷ = sync
> `+` = extra (a subset of custom)

My absolutely random ideas of the day for `userdata`:
֎ "Left-Facing Armenian Eternity Sign" [my fav]
⌬ "Benzene Ring"
⍟ "APL Functional Symbol Circle Star"
⎈ "Helm Symbol" [too small?]
⎋ "Broken Circle with Northwest Arrow"
⎊ "Circled Triangle Down"

**Comment by Revadike** [comment]
I don't know what exactly the source for `sync-community` is, but it is adding the wrong games; games I don't own. This is really annoying, please fix.
