### ISSUE TITLE
Better notifications for expiring keys and activations

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#67]
**Describe the problem that this feature would improve**
At the end of 2019, at least 19 Overwatch tradables and 61 Overwatch Loot Boxes disappeared unused because they weren't redeemed prior to the December 31, 2019 deadline. Although there are warnings about this on Barter, the date isn't visible with clicking the link. A better warning system, based on time left, would reduce the number of tradables lost.

**Describe the solution you'd like**
The activation deadline and other time-related warnings should have the relevant timestamp saved in the database and displayed with the tag. At least 24 hours prior to the deadline, a warning would appear across header of the site.

A sort option or dedicated page to all items with upcoming deadlines.

**Examples of similar solutions**
Humble shows deadlines, but they are easy to miss with a large tradable list
![image](https://user-images.githubusercontent.com/28576132/73218733-8b501500-4128-11ea-8b21-74222e533a6a.png)

**Comment by Revadike** [comment]
Be sure to also implement this for curator connect games, but mind that the expiry date of them can be extended.

**Comment by bartervg** [comment]
The activation deadlines are on a per-item_id basis. That system wouldn't work for individual curator connect games.

**Comment by Revadike** [comment]
> The activation deadlines are on a per-item_id basis. That system wouldn't work for individual curator connect games.

That seems bad. Not all games copies expire of a game, maybe only the ones from a bundle. This should be per tradable based. At least, that would make more sense to me.

**Comment by bartervg** [comment]
>  That system wouldn't work 
I wrote that too quickly. I was thinking of the Overwatch example. However, the activation tag can apply to individual tradables along with a unix timestamp. Adding better warnings for these tag could be a useful extension of the original idea.

> Not all games copies expire of a game, maybe only the ones from a bundle. 
True, but in the case of Humble Monthly activation deadlines, they've applied to most, if not all, of the tradables.

**Comment by Luckz** [comment]
My design is per-source. (Tracking curator connect expiry dates is absurd, not in scope, etc.)  
  
# Track key expiry dates, if known

## Describe the problem that this feature would improve
We don't really write down until when keys can be used, outside of sporadic bundle notes. Even when we know a specific date, we don't always add a note: https://barter.vg/i/43010/  
Sometimes, we add a note, but no trading notice, meaning no warning appears in offers.  

## Describe a solution you'd like
Ideally we could set (and track) the expiration per-source, meaning keys from one bundle or one specific giveaway have a particular expiration date, and the warning would be shown on offers only with unknown source or an at least partially matching one:  
- No source: show warning  
- Bundle site matches, bundle ID unset: show warning  
- Bundle site matches, bundle ID matches: show warning  
- Bundle site matches, bundle ID different: show no warning  

There should be different warnings depending on whether the activation date is unreached, close (~7 days?), or in the past. Warnings for expired keys could be similar to [dead platforms](https://github.com/bartervg/barter.vg/issues/102).
    
With regard to giveaways, I don't think we have a feature yet to add a tradable from a specific giveaway?  
  
  
As for notifications/user awareness, beyond site headers there's also options like Discord bot notifications, email, or a [dedicated overview page](https://github.com/bartervg/barter.vg/issues/102#issuecomment-600717317).

**Comment by Tecfan** [comment]
> At least 24 hours prior to the deadline, a warning would appear across header of the site.

For reference, we now have this in the #deadlines channel, for personal items tagged with activation deadline and have an integer tag value set.

**Comment by bartervg** [comment]
`Activation Deadline` + Unix timestamp works on a per tradable and per item basis. There isn't a top of the site warning, but there is an alert on Discord. Given that there are constantly new users adding old tradables, it's unlikely that a single 24-hour warning is preferable to the persistent item-level warning.

Looking at the tradables, saturation coverage of the expected `Call of Duty: Black Ops 4 Standard Edition` expiration doesn't seem to have had much of an effect. In addition, I'm not sure if Humble actually expired them. If they did, it's different from the Overwatch expiration.
