### ISSUE TITLE
Proper API docs

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#72]
**Describe the problem that this feature would improve**
The API is currently undocumented, leaving much to the imagination. Also, the API is prone to change, which could be confusing without any docs.

**Describe the solution you'd like**
Write docs explaining each API endpoint, their parameters and properties. 

**Examples of similar solutions**
https://developer.github.com/

**Comment by bartervg** [comment]
Revadike asks (in DM, quickly to be forgotten), 
>in https://barter.vg/u/48e/o/4042608/json whats the difference between
"quantity": 1,
        "tradable_quantity": 1,

"quantity" the quantity set in the offer, i.e. offered 1 of this
"tradable_quantity" the quantity of tradable, there is 1of this available

**Comment by bartervg** [comment]
https://github.com/bartervg/barter.vg/wiki
