### ISSUE TITLE
Remove HTML entity encoding in API

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#73]
**Describe the bug**
Symbols get encoded to their equivalent HTML entity code in the returned JSON, which can be undesirable if your program doesn't output HTML. 

**Steps to reproduce the bug**
https://barter.vg/u/48e/o/3215248/json `from_username` and `to_username` property values

**Expected behavior**
Show the actual symbol/ascii character.

**Comment by bartervg** [comment]
This was more difficult to fix than it should have been. Therefore, I limited the fix to the to and from usernames, game and bundle titles.

In addition, I switched from using `htmlentities` to `htmlspecialchars`. This should reduce the occurrences of HTML entity codes. Am I right to think there is no benefit to encoding your name as `Revad&iacute;ke`?

I did not look at other APIs, but this instance appears to be fixed, therefore closing issue.
