### ISSUE TITLE
Game Pass includes Console and PC without distinction

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#80]
**Describe the bug**
Xbox Game Pass tracking bundle show games without distinguishing if they're available on console, PC or both.

**Steps to reproduce the bug**
1. Go to https://barter.vg/bundle/3937/
2. Attempt to determine which are for PC and which are for console
3. Without going to official Xbox page, it's not possible to determine

**Expected behavior**  
Use tags similar to xbox.com showing console, PC, or both

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/28576132/75028245-ee09a780-546d-11ea-9e8d-320fdb08d564.png)

**Device (if relevant)**
N/A

**Additional context**
thanks to luckz for reporting this bug

**Comment by Luckz** [comment]
> thanks to luckz for reporting this bug

This does not mean that I believe we should be tracking subscriptions at all, or even console subscriptions. 🤗
