### ISSUE TITLE
Search does not use previous titles

### ISSUE THREAD

**Issue by bartervg** [bartervg/barter.vg#81]
**Describe the bug**
Searching `Robothorium` redirects to https://barter.vg/i/40983/
Searching `Robothorium: Sci-fi Dungeon Crawler` leads to search results where Robothorium is 7th on the list despite `Robothorium: Sci-fi Dungeon Crawler` being an exact match of a previous title. The previous titles are saved in the database and correctly match when adding tradables.

**Steps to reproduce the bug**
1. Find a game that has changed titles like Robothorium
2. Search for the game using the old title
3. Not redirected to exact match

**Expected behavior**
If the previous title is saved and it's a distinct exact match, searchers should be redirected to the profile page. Optional, display previous titles in the search results.

**Screenshots (if applicable)**

## Robothorium
![image](https://user-images.githubusercontent.com/28576132/75089925-a6e1ec00-552b-11ea-9618-f1bf6e7a7b7d.png)
...
![image](https://user-images.githubusercontent.com/28576132/75089927-acd7cd00-552b-11ea-9bc5-4ca40d642284.png)

## Robothorium: Sci-fi Dungeon Crawler  
![image](https://user-images.githubusercontent.com/28576132/75089931-b82af880-552b-11ea-8c96-3da25e211381.png)
...
![image](https://user-images.githubusercontent.com/28576132/75089934-c11bca00-552b-11ea-92d6-57edf6e9857f.png)

**Device (if relevant)**
N/A

**Additional context**
Thanks to luckz

**Comment by Luckz** [comment]
It's more "search has issues with special characters" where ":" is an example of one.

**Comment by bartervg** [comment]
It shouldn't, special characters are (sometimes) ignored. Search results for `Robothorium: Sci-fi Dungeon Crawler` and `Robothorium Scifi Dungeon Crawler` are identical.

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/77501526-adb39580-6e2e-11ea-8e69-4916f114e4f2.png)
leads to an exact match
![image](https://user-images.githubusercontent.com/28576132/77501543-bb691b00-6e2e-11ea-87d6-3dba37f0eee1.png)

Full search results
![image](https://user-images.githubusercontent.com/28576132/77501621-ef444080-6e2e-11ea-8079-341a09dbadf6.png)

However, it is fragile. Anything less than an exact match leads to
![image](https://user-images.githubusercontent.com/28576132/77501644-fff4b680-6e2e-11ea-83e8-f2ed43d53008.png)
