### ISSUE TITLE
Resubmitting propose offer form causes 2 activity entries

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#83]
## Describe the bug
Resubmitting propose offer form causes 2 activity entries.

## Steps to reproduce the bug
Resubmit propose offer form

## Expected behavior
Only 1 activity entry.

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/4411977/75095016-e42c9500-5590-11ea-872f-8cd2e939635b.png)

### Additional context
Chrome allows you to refresh the page and resubmit form.

**Comment by bartervg** [comment]
I cannot reproduce this by resubmitting the form. I reloaded the page, went back, clicked the Send button multiple times, 1 activity entry. https://barter.vg/u/a0/o/3268349/ 

Once the offer status changes from creating to proposed, additional proposed actions should be ignored. However, it looks like there's small race condition window where multiple requests occur prior to any one of them switching the status to proposed.
```php
if(status == 'creating'){
    setFromStatus('proposed'); 
    // ...
    UPDATE offers SET from_expire = ? WHERE id = ? 
    return affected_rows; 
}
```

**Comment by bartervg** [comment]
https://barter.vg/u/48e/o/3266678/
This was not a duplicate activity. It was proposed, edited, proposed, One option to clarify this would be to add edited to the feed, but not going to do so at this time.
