### ISSUE TITLE
Colorcode game titles

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#85]
![image](https://user-images.githubusercontent.com/4411977/75097991-6e84f100-55b1-11ea-9b19-ed443c1adaf5.png)

Color owned game titles green and wishlisted games another color. While we await any automatic options, this will help us manually edit pending offers to remove owned games.

**Comment by bartervg** [comment]
There's already a lot of color on that page. Perhaps _italics_ if the game is in library. Although, this will not be effective if some games are not shown, so perhaps this would need reordering also.

**Comment by Revadike** [comment]
> There's already a lot of color on that page. Perhaps _italics_ if the game is in library. Although, this will not be effective if some games are not shown, so perhaps this would need reordering also.

I only see blue/purple. You could definitely add more color.

**Comment by bartervg** [comment]
There's green, gray, red and white also. While more color are possible, it risks becoming 
![image](https://user-images.githubusercontent.com/28576132/75113402-c22c2480-561b-11ea-8e23-ac4c63407c4d.png) 
And even there, green / red / white / yellow are the primary colors.

**Comment by Revadike** [comment]
Are we sure we're looking at the same page?
![image](https://user-images.githubusercontent.com/4411977/75113980-b576f300-5652-11ea-90fa-944b1397d2e7.png)

I only meant on this page

**Comment by bartervg** [comment]
Green 
![image](https://user-images.githubusercontent.com/28576132/75114041-c0189480-5620-11ea-90e2-fc161c31d209.png)
Gray 
![image](https://user-images.githubusercontent.com/28576132/75114048-cb6bc000-5620-11ea-8e07-3645278a2931.png)
Red
![image](https://user-images.githubusercontent.com/28576132/75114061-e50d0780-5620-11ea-8caa-19be2194dabe.png)
White
![image](https://user-images.githubusercontent.com/28576132/75114073-f7874100-5620-11ea-8b07-b72f82f4ff0c.png)
In addition to pale red for cancelled and purplish blue for visited links

**Comment by Revadike** [comment]
I just meant the game titles

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/75114380-d12fc880-5655-11ea-8425-160499dc7ac0.png)

**Comment by bartervg** [comment]
Would icons (⇄★📚︎) satisfy this request?

**Comment by Revadike** [comment]
I have a better idea: Highlight all the same titles on hover. Only working with javascript. You gotta add a data (app)id attribute to each element, then:
```
[...document.querySelectorAll("[data-hover-appid]")].forEach(elem => {

elem.addEventListener("mouseenter", (event) => {
let appid = elem.dataset.hoverAppid;
[...document.querySelectorAll("[data-hover-appid=" + appid + "]")].forEach(e => {
e.style.fontWeight = "bold";
});
});

elem.addEventListener("mouseleave", (event) => {
let appid = elem.dataset.hoverAppid;
[...document.querySelectorAll("[data-hover-appid=" + appid + "]")].forEach(e => {
e.style.fontWeight = "normal";
});
});
});

**Comment by bartervg** [comment]
I added `data-appid` for each linked title, however it displays the ID associated with the platform, so it could be subID if it's a package, or if it's a non-Steam game and the ID is in the database.

**Comment by Revadike** [comment]
Works
![image](https://user-images.githubusercontent.com/4411977/106342222-65f86880-62a0-11eb-9fad-b65804ffd5aa.png)

[...document.querySelectorAll("[data-appid]")].forEach(elem => {

    elem.addEventListener("mouseenter", (event) => {
        let appid = elem.dataset.appid;
        [...document.querySelectorAll("[data-appid=\"" + appid + "\"]")].forEach(e => {
            e.style.fontWeight = "bold";
        });
    });

    elem.addEventListener("mouseleave", (event) => {
        let appid = elem.dataset.appid;
        [...document.querySelectorAll("[data-appid=\"" + appid + "\"]")].forEach(e => {
            e.style.fontWeight = "normal";
        });
    });
});

**Comment by bartervg** [comment]
Did you want to contribute it to utils.js on the develop branch?

**Comment by Luckz** [comment]
> Would icons (⇄★📚︎) satisfy this request?

It's a bit of an anti-pattern in the sense that it encourages not going through the motions of opening the offer, reading whatever message and overview text the other trader has, and seeing the full list of games when it's 20+.
(The idea of showing whether an offer has been accessed is to encourage loading that page and dealing with it, right?)

I was under the impression that the offers page also shows only a partial game list (except for on mouseover) for similar reasons, to _make you_ look at the entire offer.
If the userbase at large gets the ability to create conditional offers (where some game choices are mandatory), I doubt this can be expressed nicely on the offers page without using a humongous amount of vertical space for each such offer.


Of course the userbase & site admins are free to redecide that the offers page should be the main hub of offer investigation. Then disregard everything I said above, turn the ship around, and nicely display every item in an offer etc on the overview.


[I suppose Barter 2.x could have flip-open offers without navigating away from the list. As long as you don't want to edit them too much, anyway.]



> I have a better idea: Highlight all the same titles on hover. 

Sending out dozens of offers for/with the same stuff is another thing one might not want to encourage in the first place.

**Comment by bartervg** [comment]
I added this as highlighter.js to the rarely used dev channel of the site. Alexandra and Revadike are the only ones on it. I don't think there's a option to change this in the preferences. I'll have to modify it manually for anyone else that wants to test it.

It seems to work well. I don't notice performance problems, although maybe with enough links, it would be one. My problem with changing normal to bold and back is the layout shift of the text. 

This is more an appID problem than an implementation problem:
![image](https://user-images.githubusercontent.com/28576132/106405552-935e2700-6404-11eb-8421-e342ac38af4f.png)

**Comment by Revadike** [comment]
You can use itemid instead

**Comment by bartervg** [comment]
> 
> 
> You can use itemid instead

In that case, why use data-appid? The itemid is in the link. Would this work? `querySelectorAll("a[href=\"https://barter.vg/i/"+ itemid +"/\"]");`

**Comment by Revadike** [comment]
I suppose so, but it makes for a nicer code.

**Comment by bartervg** [comment]
`data-appid` doesn't display if empty value. There's still the potential for appID to equal subID

**Comment by Revadike** [comment]
Wouldn't itemid solve this?

**Comment by bartervg** [comment]
> 
> 
> Wouldn't itemid solve this?

Yes, it would, but wouldn't data-itemid be duplicating information? Yes, the code doesn't look as nice, but there would be thousands of extra data-itemid attributes.

**Comment by Revadike** [comment]
Well, its either that, or add an identifiable class, because otherwise the selector would become complex and easily to break.

**Comment by bartervg** [comment]
complexity!
```js
[...document.querySelectorAll("a[href^=\"https://barter.vg/i/\"]")].forEach(elem => {

    elem.addEventListener("mouseenter", (event) => {
        [...document.querySelectorAll("a[href=\"" + elem.href + "\"")].forEach(e => {
            e.style.fontWeight = "bold";
        });
    });

    elem.addEventListener("mouseleave", (event) => {
        [...document.querySelectorAll("a[href=\"" + elem.href + "\"")].forEach(e => {
            e.style.fontWeight = "normal";
        });
    });
    
});
```
To be fair, my first draft was a complexity monstrosity, and side effects would include bolding links unrelated to offers.

Design question: instead of this `e.style.fontWeight = "normal";` why not set to null or `e.style.removeProperty("font-weight");`?

**Comment by Revadike** [comment]
Hehe, now you're just gonna end up highlighting all item links on the page. You only want to highlight the games in the offers. That's what I meant with more complex selector. You gotta make sure you dont select some stray link.

**Comment by bartervg** [comment]
If the script is served on the offer section only, there are no stray links matching https://barter.vg/i/ and if there were, the consequence of highlighting them is small.

What about removeProperty or setting to null?

**Comment by Revadike** [comment]
Seems like bad design anyway. Idk what u mean with removeproperty or setting to null.

**Comment by bartervg** [comment]
> 
> 
> Seems like bad design anyway. Idk what u mean with removeproperty or setting to null.

e.style.removeProperty("font-weight");

**Comment by Revadike** [comment]
> > Seems like bad design anyway. Idk what u mean with removeproperty or setting to null.
> 
> e.style.removeProperty("font-weight");

Sure, u can do that instead

**Comment by Revadike** [comment]
I hate to say it, but the current implementation isn't very helpful. I think we better find another solution. The original problem was to find offers with a certain game, but a search option is probably better for that.

**Comment by Revadike** [comment]
So, we're keeping it anyway?

**Comment by bartervg** [comment]
You want me to remove it from the beta build of the site?

**Comment by Revadike** [comment]
> You want me to remove it from the beta build of the site?

Ye I don't think it's that helpful in its current form.

**Comment by bartervg** [comment]
It should be removed now. Thank you for beta testing it for 21 (!) months.
