### ISSUE TITLE
Wrong number of items tagged is shown when you update an existing trade tag with a new integer tag value from your tradables list

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#94]
## Describe the bug
When you update the tags on your games in your tradable list and press "Tag", a message appears on the top of the page. For example, if you add "userfield" to a game, with an integer tag value of "10", it will show you this message: "Updated 1 item tagged".

If you then were to update the integer tag value from "10" to "15", still only having this one item selected, you will get the following message: "Updated 2 items tagged". This is wrong – only 1 item was tagged.

If you update the integer tag value of 5 items at the same time, it will then tell you that you updated 10 items (it doubles).

This is true for all trading tags when you use the integer tag value field. The "integer tag value" field can also be empty for the bug to appear. For example, if you add the tag "combined" with no integer value, and then update it to any number in a second action, you will still see "2 items tagged", when you only tagged 1 item.

See screenshot for more context. Only 1 item is selected, but the system claims that it updated 2 items. 
![image](https://user-images.githubusercontent.com/956878/76165132-d19b8980-6154-11ea-8ab5-7af6155684f8.png)

**Comment by bartervg** [comment]
This appears to be the cause of the bug https://www.php.net/manual/en/mysqli.affected-rows.php#102523 
> +1: a row was inserted
+2: a row was updated

**Comment by bartervg** [comment]
previously: items_tagged += affected_rows
currently: if(affected_rows > 0){ items_items += 1 }

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/76358563-07c14080-62f0-11ea-98ca-4369bae07635.png)
![image](https://user-images.githubusercontent.com/28576132/76358550-02fc8c80-62f0-11ea-986f-eb3f84b4d213.png)

upon update of tag
![image](https://user-images.githubusercontent.com/28576132/76358596-14de2f80-62f0-11ea-8588-621ddaa66c25.png)
![image](https://user-images.githubusercontent.com/28576132/76358619-19a2e380-62f0-11ea-9b48-d865a3b82acb.png)

It looks to be fixed although it is likely that I used ON DUPLICATE KEY UPDATE and += affected_rows in other areas of the site.
